// Mock-test data layer.
//
// IMPORTANT: The full per-topic question files live under public/mocks/*.json
// and are served as STATIC ASSETS by the CDN — they are never bundled into
// the Cloudflare Worker. Only a small metadata manifest is bundled at build
// time (generated by scripts/build_mock_manifest.mjs).
//
// On-disk file shapes (in public/mocks/*.json):
//   v1 (legacy):  { topic, tests: [ { slug, mockNumber, title, questions: RawQuestion[] } ] }
//   v2 (bank):    { version: 2, topic, bank: RawQuestion[], mocks: [ { mockNumber, title, questionIds: string[] } ] }
import type { Quiz, Question } from "@/data/quizzes";
import { categories, findTopic } from "@/data/categories";

/**
 * Smart, non-duplicating mock-test title.
 *   "Driving Theory Test"          -> "Driving Theory Mock Test 1"
 *   "Hazard Perception Test"       -> "Hazard Perception Mock Test 1"
 *   "Private Hire Driver Licence"  -> "Private Hire Driver Licence Mock Test 1"
 */
export function smartMockTitle(topicTitle: string, n: number): string {
  const base = topicTitle.replace(/\s+(?:mock\s+)?test$/i, "").trim();
  return `${base} Mock Test ${n}`;
}


export function smartMockTitleFromSlug(topicSlug: string, n: number): string {
  const t = findTopic(topicSlug)?.topic.title ?? topicSlug;
  return smartMockTitle(t, n);
}

// ---------- Raw on-disk question shapes (one per supported type) ----------

type RawMcq = {
  type?: "mcq" | "multiple_choice";
  id?: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  image?: string;
  imageAlt?: string;
};
type RawFillBlanks = {
  type: "fill-blanks" | "dropdown_blanks";
  id?: string;
  template: string;
  prompt?: string;
  blanks: { options: string[]; correctIndex: number }[];
  explanation: string;
};
type RawDragDrop = {
  type: "drag-drop-blanks" | "drag_drop_blanks";
  id?: string;
  template: string;
  prompt?: string;
  blanks: { options: string[]; correctIndex: number }[];
  explanation: string;
};
type RawTrueFalse = {
  type: "true-false" | "true_false";
  id?: string;
  question: string;
  correctAnswer: boolean;
  explanation: string;
  image?: string;
  imageAlt?: string;
};
type RawMultiResponse = {
  type: "multiple-response" | "multiple_response";
  id?: string;
  question: string;
  options: string[];
  correctAnswers: number[];
  explanation: string;
  image?: string;
  imageAlt?: string;
};
type RawNumeric = {
  type: "numeric-entry" | "numeric_entry";
  id?: string;
  question: string;
  correctAnswer: number;
  tolerance?: number;
  unit?: string;
  explanation: string;
};
type RawImage = {
  type: "image-question" | "image_question";
  id?: string;
  question: string;
  image?: string;
  imageAlt: string;
  imageDescription?: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
};
type RawHotSpot = {
  type: "hot-spot" | "hot_spot";
  id?: string;
  question: string;
  image: string;
  imageAlt: string;
  spots: { id: string; label: string; x: number; y: number; w: number; h: number }[];
  correctSpotId: string;
  explanation: string;
};

type RawQuestion =
  | RawMcq
  | RawFillBlanks
  | RawDragDrop
  | RawTrueFalse
  | RawMultiResponse
  | RawNumeric
  | RawImage
  | RawHotSpot;

// ---------- Internal mock shape consumed by routes ----------

export type MockTest = {
  slug: string;
  topic: string;
  mockNumber: number;
  title: string;
  questions: RawQuestion[];
};

type V1File = { topic: string; tests: MockTest[] };
type V2File = {
  version: 2;
  topic: string;
  bank: (RawQuestion & { id: string })[];
  mocks: { mockNumber: number; title: string; questionIds: string[] }[];
};
type MockFile = V1File | V2File;

// ---------- Manifest (small, bundled) ----------

type ManifestMock = {
  mockNumber: number;
  slug: string;
  title: string;
  questionCount: number;
};
type ManifestEntry = { topic: string; file: string; mocks: ManifestMock[] };

const topicSlugs = new Set(
  categories.flatMap((category) => category.topics.map((topic) => topic.slug)),
);

function buildTopicEntry(topic: string): ManifestEntry | undefined {
  if (!topicSlugs.has(topic)) return undefined;
  return {
    topic,
    file: `${topic}.json`,
    mocks: Array.from({ length: TOTAL_MOCKS_PER_TOPIC }, (_, i) => {
      const mockNumber = i + 1;
      return {
        mockNumber,
        slug: `${topic}-mock-${mockNumber}`,
        title: `Mock Test ${mockNumber}`,
        questionCount: QUESTIONS_PER_MOCK,
      };
    }),
  };
}

// Reverse index: slug -> topic, populated lazily on first lookup.
let slugToTopic: Map<string, string> | null = null;
function getSlugIndex(): Map<string, string> {
  if (slugToTopic) return slugToTopic;
  const m = new Map<string, string>();
  for (const topic of topicSlugs) {
    for (let i = 1; i <= TOTAL_MOCKS_PER_TOPIC; i++) {
      m.set(`${topic}-mock-${i}`, topic);
    }
  }
  slugToTopic = m;
  return m;
}

export const TOTAL_MOCKS_PER_TOPIC = 45;
export const QUESTIONS_PER_MOCK = 24;

// ---------- Lazy loader for full mock files ----------

// Per-topic in-memory cache. Stores the raw file (deduped fetch promise).
// Runtime quiz pages use this cache; admin reads bypass it so CSV commits are
// visible from GitHub main without waiting for the next static deploy/cache.
const fileCache = new Map<string, Promise<MockFile | undefined>>();

function isV2(file: MockFile): file is V2File {
  return (file as V2File).version === 2 && Array.isArray((file as V2File).bank);
}

/**
 * Resolve `/mocks/foo.json` to an absolute URL during SSR (Cloudflare Worker
 * runtime requires absolute URLs for `fetch`). On the client, relative paths
 * resolve against window.location naturally.
 */
function resolveMockUrl(path: string): string {
  if (typeof window !== "undefined") return path;
  // Server: try the in-flight request origin (set by the SSR entry), then
  // fall back to env-configured site URL, then a hard-coded production URL.
  const g = globalThis as { __MOCK_BASE_URL__?: string };
  const base =
    g.__MOCK_BASE_URL__ ||
    (typeof process !== "undefined" && process.env?.SITE_URL) ||
    "https://www.uktesthub.com";
  return new URL(path, base).toString();
}

async function fetchMockFile(url: string, onFailure?: () => void): Promise<MockFile | undefined> {
  try {
    const res = await fetch(url);
    if (!res.ok) return undefined;
    return (await res.json()) as MockFile;
  } catch {
    onFailure?.();
    return undefined;
  }
}

async function loadTopicFile(topic: string): Promise<MockFile | undefined> {
  const entry = buildTopicEntry(topic);
  if (!entry) return undefined;
  const cached = fileCache.get(topic);
  if (cached) return cached;
  const url = resolveMockUrl(`/mocks/${entry.file}`);
  const promise = fetchMockFile(url, () => fileCache.delete(topic));
  fileCache.set(topic, promise);
  return promise;
}

export function invalidateTopicFileCache(topic?: string) {
  if (topic) fileCache.delete(topic);
  else fileCache.clear();
}

function isValidRawQuestion(q: RawQuestion): boolean {
  // Normalise underscore variants from the spreadsheet/AI to the hyphen
  // variants used at runtime so both shapes validate identically.
  const t = ((q as { type?: string }).type ?? "mcq").replace(/_/g, "-");
  switch (t) {
    case "mcq":
    case "multiple-choice":
    case "image-question":
      return Array.isArray((q as RawMcq).options) && (q as RawMcq).options.length > 0;
    case "multiple-response":
      return (
        Array.isArray((q as RawMultiResponse).options) &&
        Array.isArray((q as RawMultiResponse).correctAnswers)
      );
    case "fill-blanks":
    case "dropdown-blanks":
    case "drag-drop-blanks": {
      const blanks = (q as RawFillBlanks).blanks;
      if (!Array.isArray(blanks)) return false;
      const text =
        (q as RawFillBlanks & { question?: string; template?: string }).question ??
        (q as RawFillBlanks & { template?: string }).template ??
        "";
      const placeholderIndices = [...text.matchAll(/\{\{(\d+)\}\}/g)].map((m) =>
        Number(m[1]),
      );
      const placeholderCount = placeholderIndices.length
        ? Math.max(...placeholderIndices) + 1
        : 0;
      // Reject malformed entries where placeholder count and blank count disagree.
      if (placeholderCount !== blanks.length) {
        if (typeof console !== "undefined") {
          console.warn(
            `[mocks] Dropping malformed ${t} question ${(q as { id?: string }).id ?? "?"}: ${placeholderCount} placeholders vs ${blanks.length} blanks`,
          );
        }
        return false;
      }
      return true;
    }
    case "hot-spot":
      return (
        typeof (q as RawHotSpot).image === "string" &&
        Array.isArray((q as RawHotSpot).spots) &&
        (q as RawHotSpot).spots.length > 0
      );
    case "true-false":
      return typeof (q as RawTrueFalse).correctAnswer === "boolean";
    case "numeric-entry":
      return typeof (q as RawNumeric).correctAnswer === "number";
    default:
      return false;
  }
}

function extractMockFromFile(
  file: MockFile,
  mockNumber: number,
): MockTest | undefined {
  if (isV2(file)) {
    const m = file.mocks.find((x) => x.mockNumber === mockNumber);
    if (!m) return undefined;
    const bankById = new Map(file.bank.map((q) => [q.id, q]));
    const questions: RawQuestion[] = [];
    for (const qid of m.questionIds) {
      const q = bankById.get(qid);
      if (q && isValidRawQuestion(q)) questions.push(q);
    }
    return {
      slug: `${file.topic}-mock-${mockNumber}`,
      topic: file.topic,
      mockNumber,
      title: m.title,
      questions,
    };
  }
  const t = file.tests.find((x) => x.mockNumber === mockNumber);
  if (!t) return undefined;
  return {
    ...t,
    slug: t.slug ?? `${file.topic}-mock-${mockNumber}`,
    topic: file.topic,
    questions: (t.questions ?? []).filter(isValidRawQuestion),
  };
}

/**
 * Lazily load a single mock by its slug. Fetches the topic's static JSON
 * from /mocks/<file> on demand and extracts only the requested mock.
 */
export async function loadMockBySlug(slug: string): Promise<MockTest | undefined> {
  const topic = getSlugIndex().get(slug);
  if (!topic) return undefined;
  const match = /-mock-(\d+)$/.exec(slug);
  if (!match) return undefined;
  const mockNumber = parseInt(match[1], 10);
  const file = await loadTopicFile(topic);
  if (!file) return undefined;
  return extractMockFromFile(file, mockNumber);
}

/**
 * Load the entire raw topic file (used by the admin question browser).
 */
export async function loadTopicFileForAdmin(
  topic: string,
): Promise<MockFile | undefined> {
  const entry = buildTopicEntry(topic);
  if (!entry) return undefined;

  // Admin must show the same source of truth that CSV import writes to. Fetch
  // the committed file from GitHub main first, then fall back to the deployed
  // static asset if GitHub is temporarily unavailable.
  const githubUrl = `https://raw.githubusercontent.com/soldier9918/uktesthub/main/public/mocks/${entry.file}?t=${Date.now()}`;
  const fresh = await fetchMockFile(githubUrl);
  if (fresh) {
    fileCache.set(topic, Promise.resolve(fresh));
    return fresh;
  }

  const deployedUrl = `${resolveMockUrl(`/mocks/${entry.file}`)}?t=${Date.now()}`;
  const deployed = await fetchMockFile(deployedUrl);
  if (deployed) {
    fileCache.set(topic, Promise.resolve(deployed));
    return deployed;
  }
  return undefined;
}

/**
 * Synchronous metadata helpers — backed only by the small manifest, safe
 * for use in route loaders, sitemaps and category/topic pages.
 */
export function getTopicManifest(topic: string): ManifestEntry | undefined {
  return buildTopicEntry(topic);
}

export function listAllTopics(): ManifestEntry[] {
  return Array.from(topicSlugs)
    .map((topic) => buildTopicEntry(topic))
    .filter((entry): entry is ManifestEntry => Boolean(entry));
}

export function listMockSlots(topicSlug: string) {
  const entry = buildTopicEntry(topicSlug);
  const realByNum = new Map((entry?.mocks ?? []).map((m) => [m.mockNumber, m]));
  return Array.from({ length: TOTAL_MOCKS_PER_TOPIC }, (_, i) => {
    const n = i + 1;
    const m = realByNum.get(n);
    return {
      mockNumber: n,
      slug: m?.slug ?? `${topicSlug}-mock-${n}`,
      title: m?.title ?? `Test ${n}`,
      available: Boolean(m),
      questionsCount: m?.questionCount ?? QUESTIONS_PER_MOCK,
    };
  });
}

// ---------- Raw → typed Question converter ----------

function normaliseType(raw: RawQuestion): string {
  const t = (raw as { type?: string }).type;
  if (!t) return "mcq";
  // Underscore variants from the spreadsheet/AI → hyphen variants the runtime uses.
  return t.replace(/_/g, "-");
}

function rawToQuestion(raw: RawQuestion, idx: number): Question {
  const id = idx + 1;
  const t = normaliseType(raw);

  switch (t) {
    case "fill-blanks":
    case "dropdown-blanks": {
      const r = raw as RawFillBlanks;
      return {
        type: "fill-blanks",
        id,
        template: r.template,
        prompt: r.prompt,
        blanks: r.blanks,
        explanation: r.explanation,
      };
    }
    case "drag-drop-blanks": {
      const r = raw as RawDragDrop;
      return {
        type: "drag-drop-blanks",
        id,
        template: r.template,
        prompt: r.prompt,
        blanks: r.blanks,
        explanation: r.explanation,
      };
    }
    case "true-false": {
      const r = raw as RawTrueFalse;
      return {
        type: "true-false",
        id,
        question: r.question,
        correctAnswer: r.correctAnswer,
        explanation: r.explanation,
        image: r.image,
        imageAlt: r.imageAlt,
      };
    }
    case "multiple-response": {
      const r = raw as RawMultiResponse;
      return {
        type: "multiple-response",
        id,
        question: r.question,
        options: r.options,
        correctAnswers: r.correctAnswers,
        explanation: r.explanation,
        image: r.image,
        imageAlt: r.imageAlt,
      };
    }
    case "numeric-entry": {
      const r = raw as RawNumeric;
      return {
        type: "numeric-entry",
        id,
        question: r.question,
        correctAnswer: r.correctAnswer,
        tolerance: r.tolerance,
        unit: r.unit,
        explanation: r.explanation,
      };
    }
    case "image-question": {
      const r = raw as RawImage;
      // No image URL — fold the description into the question text so the
      // question is self-contained instead of misleadingly referring to a
      // missing image.
      if (!r.image) {
        const desc = r.imageDescription || r.imageAlt || "";
        const cleanedQ = (r.question || "")
          .replace(
            /this (mandatory blue|blue circular|red triangular|yellow|warning|prohibition|circular|mandatory|hazard|safety)? ?sign/gi,
            "the sign",
          )
          .replace(/this (image|picture|diagram|illustration)/gi, "the $1")
          .replace(/shown (above|here|below)/gi, "")
          .replace(/\s+/g, " ")
          .trim();
        const composed = desc
          ? `${desc.replace(/\s*\.?\s*$/, ".")} ${cleanedQ}`
          : cleanedQ;
        return {
          type: "mcq",
          id,
          question: composed,
          options: r.options,
          correctAnswer: r.correctAnswer,
          explanation: r.explanation,
        };
      }
      return {
        type: "image-question",
        id,
        question: r.question,
        image: r.image,
        imageAlt: r.imageAlt,
        options: r.options,
        correctAnswer: r.correctAnswer,
        explanation: r.explanation,
      };
    }
    case "hot-spot": {
      const r = raw as RawHotSpot & { imageDescription?: string };
      // Hot-spot without an image URL can't be rendered — skip in a safe way
      // by converting to a basic MCQ if options exist; otherwise return a
      // placeholder MCQ so the mock still has the right number of questions.
      if (!r.image) {
        return {
          type: "mcq",
          id,
          question: r.question,
          options: r.spots.map((s) => s.label),
          correctAnswer: Math.max(
            0,
            r.spots.findIndex((s) => s.id === r.correctSpotId),
          ),
          explanation: r.explanation,
        };
      }
      return {
        type: "hot-spot",
        id,
        question: r.question,
        image: r.image,
        imageAlt: r.imageAlt,
        spots: r.spots,
        correctSpotId: r.correctSpotId,
        explanation: r.explanation,
      };
    }
    case "mcq":
    case "multiple-choice":
    default: {
      const r = raw as RawMcq;
      return {
        type: "mcq",
        id,
        question: r.question,
        options: r.options,
        correctAnswer: r.correctAnswer,
        explanation: r.explanation,
        image: r.image,
        imageAlt: r.imageAlt,
      };
    }
  }
}

export function mockToQuiz(category: string, mock: MockTest): Quiz {
  return {
    slug: mock.slug,
    category,
    topic: mock.topic,
    quizTitle: smartMockTitleFromSlug(mock.topic, mock.mockNumber),
    description: `Mock test ${mock.mockNumber} — ${mock.questions.length} questions.`,
    timeLimit: mock.questions.length * 60,
    difficulty: "Medium",
    passMark: 75,
    questions: mock.questions.map((raw, idx) => {
      const q = rawToQuestion(raw, idx);
      // Attach the original bank id (e.g. "sa-mc-0017") so admin overrides —
      // keyed by bank id — can be matched at render time. Falls back to a
      // deterministic synthetic id for legacy v1 files without bank ids.
      const sourceId =
        (raw as { id?: string }).id ?? `${mock.slug}-q${idx + 1}`;
      (q as unknown as { sourceId: string }).sourceId = sourceId;
      return q;
    }),
  };
}

/**
 * Build a fresh randomised exam Quiz by drawing `count` unique questions
 * from a topic's v2 bank. Used for "real exam" mode (e.g. Driving Theory:
 * 50 unique questions, 57 minutes, pass 43/50). Returns undefined if the
 * topic file is missing, not v2, or the bank is smaller than `count`.
 */
export async function buildRandomExamQuiz(
  topicSlug: string,
  opts: {
    count: number;
    timeLimitSec: number;
    passMarkPct: number;
    title: string;
    description: string;
  },
): Promise<Quiz | undefined> {
  const file = await loadTopicFile(topicSlug);
  if (!file || !isV2(file)) return undefined;
  const bank = file.bank;
  if (bank.length < opts.count) return undefined;

  // Fisher–Yates shuffle on a shallow copy, take first N → guaranteed unique.
  const pool = bank.slice();
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const picked = pool.slice(0, opts.count);

  const category = findTopic(topicSlug)?.category.slug ?? topicSlug;
  const slug = `${topicSlug}-exam`;

  return {
    slug,
    category,
    topic: topicSlug,
    quizTitle: opts.title,
    description: opts.description,
    timeLimit: opts.timeLimitSec,
    difficulty: "Medium",
    passMark: opts.passMarkPct,
    questions: picked.map((raw, idx) => {
      const q = rawToQuestion(raw, idx);
      const sourceId = (raw as { id?: string }).id ?? `${slug}-q${idx + 1}`;
      (q as unknown as { sourceId: string }).sourceId = sourceId;
      return q;
    }),
  };
}

