#!/usr/bin/env python3
"""Generate public/mocks/ucas-application-knowledge.json (v2, 45 mocks × 24 Qs)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "mocks" / "ucas-application-knowledge.json"

# (question, [opts], correctIndex, explanation)
RAW = [
    ("What does UCAS stand for?", ["Universities and Colleges Admissions Service", "University Course Application System", "United Colleges Admissions Service", "University Centralised Admission Scheme"], 0, "UCAS = Universities and Colleges Admissions Service, the UK central body for university applications."),
    ("How many course choices can you list on a standard UCAS Undergraduate application?", ["3", "4", "5", "6"], 2, "You can apply for up to 5 courses on a standard UCAS Undergraduate application."),
    ("What is the standard UCAS Undergraduate January equal-consideration deadline (most courses)?", ["15 October", "31 December", "29 January", "30 June"], 2, "The main UCAS Undergraduate equal-consideration deadline for most courses is 29 January (18:00 UK time)."),
    ("Which deadline applies to most Oxford, Cambridge, medicine, dentistry and veterinary courses?", ["29 January", "15 October", "1 September", "30 June"], 1, "The 15 October deadline applies to Oxford and Cambridge and to most medicine, dentistry and veterinary medicine/science courses."),
    ("What is 'Clearing' in UCAS?", ["A way to apply after the main deadlines or if you have no offers", "A method of withdrawing your application", "A free university tuition scheme", "An interview round for top universities"], 0, "Clearing matches applicants without a place to courses with vacancies, mainly from July onwards."),
    ("What is the UCAS 'Extra' service used for?", ["Adding more than 5 choices initially", "Applying for an extra year of study", "Choosing an additional course if you've used your 5 choices and have no offers", "Requesting extra financial support"], 2, "UCAS Extra lets you add one more course at a time, free of charge, if you've used all 5 choices and aren't holding any offers."),
    ("What is a 'firm' choice in UCAS?", ["Your first-choice offer that you definitely want to accept", "Your backup offer", "An unsuccessful application", "An unconditional offer only"], 0, "Your firm choice is the offer you most want to accept and will be your main place if you meet its conditions."),
    ("What is an 'insurance' choice?", ["A backup offer in case you miss your firm offer's conditions", "An offer that includes insurance cover", "Any unconditional offer", "The first offer you receive"], 0, "Your insurance choice is a backup, usually with lower entry requirements than your firm choice."),
    ("Roughly how long can the UCAS personal statement be?", ["1,000 characters / 30 lines", "4,000 characters / 47 lines", "10,000 characters / 100 lines", "Unlimited"], 1, "The traditional UCAS personal statement is up to 4,000 characters or 47 lines, whichever comes first."),
    ("How many references do you usually need on a UCAS Undergraduate application?", ["None", "One", "Two", "Three"], 1, "You typically need one reference, usually from a teacher, tutor or employer who knows your academic ability."),
    ("Who normally writes the UCAS reference for a school-leaver?", ["A parent", "A close friend", "A teacher or tutor", "The applicant themselves"], 2, "School and college applicants normally have their reference written by a teacher or tutor."),
    ("What is a 'conditional offer'?", ["An offer with no conditions you must meet", "An offer that depends on you meeting certain grades or other conditions", "An offer for a conditional degree", "An offer you can only accept conditionally"], 1, "A conditional offer depends on you meeting specific conditions, usually exam grades."),
    ("What is an 'unconditional offer'?", ["An offer that has no conditions left to meet", "An offer with hidden conditions", "An offer made only after results day", "An offer for unconditional loans"], 0, "An unconditional offer means the university will accept you regardless of upcoming exam results."),
    ("If you miss the conditions of both your firm and insurance offers, what is your next step likely to be?", ["You are automatically given a place", "You enter Clearing", "Your application is cancelled forever", "You must re-take A-levels"], 1, "If you don't meet either set of conditions, you'll usually enter Clearing to look for vacancies."),
    ("What is 'Adjustment' (now replaced) historically used for?", ["Swapping your firm choice for a higher-ranked one if you exceeded your offer", "Adjusting your tuition fees", "Adjusting your accommodation", "Re-taking exams"], 0, "Adjustment let students who exceeded their firm offer look for an alternative place; UCAS has since replaced it with self-release into Clearing."),
    ("Which form is used by independent (private) applicants applying through UCAS?", ["UCAS Apply as an 'individual' applicant", "UCAS Conservatoires only", "Common App", "SAAS"], 0, "Applicants not at a school/college register as individual applicants on UCAS and arrange their own reference."),
    ("How many characters are reserved for the personal statement (current limit)?", ["2,000", "3,000", "4,000", "5,000"], 2, "The personal statement is capped at 4,000 characters (including spaces) or 47 lines."),
    ("On the standard UCAS Undergraduate application, can you apply to both Oxford and Cambridge in the same cycle?", ["Yes, always", "No, you can apply to only one in the same cycle (with limited exceptions)", "Only if you have predicted A* grades", "Only via Clearing"], 1, "In general you can only apply to either Oxford or Cambridge in the same cycle (limited exceptions exist, e.g. organ scholarships)."),
    ("How many course choices can you make if you apply to medicine, dentistry, veterinary medicine or veterinary science?", ["Up to 5, any number can be in these subjects", "Up to 4 in these subjects", "Up to 3 in these subjects", "Only 1 in these subjects"], 1, "You can apply for a maximum of 4 courses in medicine, dentistry, veterinary medicine or veterinary science; the 5th must be a different subject."),
    ("What does 'UCAS Tariff' refer to?", ["A points system used by some universities to compare qualifications", "A tuition fee scale", "A travel allowance", "A loan repayment threshold"], 0, "The UCAS Tariff converts qualifications and grades into points for comparison; some universities use it for entry requirements."),
    ("Which of these is an example of a typical A-level UCAS Tariff value for an A grade?", ["32", "40", "48", "60"], 2, "An A at A-level is currently worth 48 UCAS Tariff points (A* = 56)."),
    ("How many UCAS Tariff points is an A* at A-level worth?", ["40", "48", "56", "64"], 2, "An A* at A-level is worth 56 UCAS Tariff points."),
    ("What does 'BTEC' usually refer to?", ["A vocational qualification recognised by UCAS", "A type of student loan", "A scholarship body", "A foreign exam"], 0, "BTECs are vocational qualifications that can carry UCAS Tariff points and are recognised by most UK universities."),
    ("What is the UCAS application fee for a single choice (single course)?", ["£0", "around £28.50", "around £100", "around £250"], 1, "For the 2025 cycle UCAS charged around £28.50 for one or multiple choices; check the current year's fee."),
    ("Is the UCAS application fee higher if you apply for more than one course?", ["Yes, by hundreds of pounds", "No — one flat fee covers up to 5 choices", "Only for international applicants", "Only for postgraduate courses"], 1, "One flat fee covers up to 5 undergraduate choices."),
    ("Which of the following is NOT included in a UCAS Undergraduate application?", ["Personal statement", "Reference", "Course choices", "Original certificates"], 3, "You don't upload original certificates; universities ask for proof later if needed."),
    ("What is 'Track' (now part of the UCAS Hub) used for?", ["Tracking parcels", "Tracking your UCAS application and offers", "Tracking student loans only", "Tracking accommodation"], 1, "Track / the UCAS Hub is where you monitor your application status, offers, and decisions."),
    ("By when must you usually reply to your offers if all decisions are received by early May?", ["Within 24 hours", "Within 2 weeks of the UCAS deadline given", "Within 6 months", "Never — replies are optional"], 1, "UCAS sets a reply deadline (often early-mid June) once all your decisions are in; if you miss it, offers can be declined automatically."),
    ("What does 'deferred entry' mean on a UCAS application?", ["Applying to start your course one year later than the usual entry year", "Deferring your fees", "Postponing your A-levels", "Taking a part-time route"], 0, "Deferred entry means you apply now but start the course the following academic year (e.g. for a gap year)."),
    ("Can you change your firm choice after you have accepted it?", ["Yes, freely at any time", "Only via withdrawing and re-entering Clearing/Extra under UCAS rules", "Only if your parents agree", "Only after exam results"], 1, "Once accepted, switching usually requires withdrawing and using Clearing/self-release; you can't freely swap firm choices."),
    ("Which exam is used for entry to most medical schools in the UK?", ["UCAT", "LNAT", "PAT", "ELAT"], 0, "Most UK medical schools use the UCAT (University Clinical Aptitude Test)."),
    ("Which test is required for most UK law degrees at certain universities?", ["LNAT", "UCAT", "PAT", "MAT"], 0, "The LNAT (Law National Aptitude Test) is required by several leading UK law schools."),
    ("Which test is used by Oxford Physics?", ["PAT (Physics Admissions Test)", "MAT", "TSA", "BMAT"], 0, "The Physics Admissions Test (PAT) is used by Oxford Physics."),
    ("What does 'Open day' mean in the UCAS context?", ["A day a university opens to visitors to showcase its facilities and courses", "A free tuition day", "A day off for staff", "A trial exam day"], 0, "Open days let prospective students visit campus, tour facilities and meet staff before applying."),
    ("Which of the following best describes 'predicted grades'?", ["Your final exam grades", "Grades a teacher predicts you'll achieve in your final exams", "The grades the university requires", "Past exam grades"], 1, "Predicted grades are forecasts made by your teachers and shared with universities via your reference."),
    ("If your firm choice is unconditional, do you still need to take your A-levels seriously?", ["No, results don't matter at all", "Yes, results can still affect scholarships, courses and future opportunities", "Only the English grade matters", "Only Maths matters"], 1, "Even with an unconditional offer, your final grades may matter for scholarships, alternative courses, and future job/postgraduate prospects."),
    ("Which of the following is true about the UCAS personal statement?", ["It is shared with every university you apply to", "Each university gets a different statement", "It's optional", "It's written by your school"], 0, "A single personal statement is sent to all your chosen universities."),
    ("Which UK student finance body is for English-domiciled students?", ["Student Finance England (SFE)", "SAAS", "Student Finance Wales", "Student Finance NI"], 0, "Student Finance England handles loans and grants for students who normally live in England."),
    ("Which body provides student finance to Scottish-domiciled students?", ["SAAS", "Student Finance England", "Student Finance Wales", "Student Loans Company NI"], 0, "SAAS (Student Awards Agency Scotland) administers funding for Scottish-domiciled students."),
    ("Roughly when does the UCAS Undergraduate application normally open for the next cycle?", ["January", "March", "May", "September"], 2, "The UCAS Undergraduate application typically opens in May of the previous year for the next cycle."),
    ("Roughly when does the next-cycle UCAS Undergraduate cycle open for submission of applications?", ["May", "Early September", "December", "March"], 1, "Applications can usually start being submitted from early September of the year before entry."),
    ("What is the latest 'on time' UCAS Undergraduate deadline for most courses (most recent cycle)?", ["15 October", "29 January", "30 June", "20 September"], 1, "For most courses the on-time equal-consideration deadline is 29 January."),
    ("What happens to applications submitted after 30 June?", ["They are automatically accepted", "They are entered directly into Clearing", "They are forwarded to the next cycle", "They are rejected"], 1, "Applications submitted after 30 June are automatically entered into Clearing."),
    ("What is the final Clearing deadline (roughly)?", ["Mid-October", "December", "March", "May"], 0, "Clearing typically closes in mid-October each year."),
    ("Which qualification is administered by Cambridge for some degrees?", ["TMUA / ESAT (replacing some earlier tests)", "UCAT", "LNAT", "QTS"], 0, "Cambridge uses tests like the TMUA and (more recently) the ESAT for selected subjects."),
    ("Which document do universities use to verify your qualifications later?", ["Original certificates or verified results from the exam board", "Your personal statement", "Your reference letter", "Your UCAS Hub login"], 0, "Universities require evidence of your qualifications, usually via original certificates or verified results from your exam board."),
    ("Where is the 'employment history' section on a UCAS application?", ["Personal statement", "Reference", "Education section", "A dedicated 'Employment' section"], 3, "UCAS has a dedicated Employment section for paid jobs; unpaid work usually goes in the personal statement."),
    ("Which of these qualifications carries UCAS Tariff points?", ["A-levels, BTECs, Highers, IB, EPQ and many more", "Only A-levels", "Only IB", "Only T-levels"], 0, "Many UK and international qualifications carry UCAS Tariff points, including A-levels, BTECs, Scottish Highers, IB, EPQ and T Levels."),
    ("Which qualification is the EPQ?", ["Extended Project Qualification", "European Programme Qualification", "English Performance Qualification", "Engineering Practice Qualification"], 0, "The EPQ is the Extended Project Qualification, worth UCAS Tariff points and often valued by universities."),
    ("What does 'IB' stand for?", ["International Baccalaureate", "Intermediate Bachelor", "Independent Board", "International Bursary"], 0, "IB stands for International Baccalaureate, an internationally recognised pre-university qualification."),
    ("What is a 'foundation year'?", ["An optional Year 0 before Year 1, designed to prepare students for degree-level study", "A postgraduate qualification", "A pre-school year", "A funded gap year"], 0, "A foundation year (often Year 0) prepares students who may not yet meet standard entry requirements for their chosen degree."),
    ("Which of these is true about apprenticeships compared to UCAS Undergraduate applications?", ["Apprenticeships are arranged with employers, not via UCAS Undergraduate", "Apprenticeships are applied for only through UCAS", "Apprenticeships replace all UCAS applications", "Apprenticeships are only available to mature students"], 0, "Most apprenticeships are advertised by employers/providers and applied to directly, not via the UCAS Undergraduate scheme."),
    ("How should you write your personal statement?", ["Reuse a template from the internet word-for-word", "In your own words, focused on your motivation, skills and experiences", "Only in bullet points", "In the third person"], 1, "UCAS uses similarity-detection software; statements should be original and reflect your motivation, skills and relevant experiences."),
    ("What does UCAS do if your personal statement is flagged for plagiarism?", ["Nothing", "Universities are notified, which can lead to rejection", "Your application is deleted", "You get a refund"], 1, "If similarity is detected, UCAS notifies your chosen universities, which can affect their decision."),
    ("In the UCAS application, who can act as a referee?", ["A teacher, tutor, employer or other professional who knows your academic ability/character", "A close family member", "A friend the same age as you", "A celebrity"], 0, "References should come from a teacher, tutor, employer, or another professional — not a family member or friend."),
    ("What is the 'UCAS Hub'?", ["UCAS's online portal for applicants to research, apply and track decisions", "A physical office in London", "A magazine", "A campus shop"], 0, "The UCAS Hub is the online portal used to apply and manage your application."),
    ("If you change your mind about your course before submission, can you edit your application?", ["Yes, until you submit it", "No, never", "Only after results day", "Only for a fee"], 0, "You can edit your application freely until it is submitted; after submission you can only make limited changes via your university or UCAS."),
    ("Which is true about offer holder days?", ["They're for applicants holding an offer to learn more before deciding", "They're only for international applicants", "They replace open days for everyone", "They are paid events"], 0, "Offer holder days target applicants who already hold an offer and want to learn more before firming."),
    ("Which is true about deferring AFTER getting an offer?", ["You must always ask the university to defer; it is not automatic", "All offers automatically allow deferral", "You can defer for 5 years", "You must reapply via UCAS in a new cycle"], 0, "Deferral is at the university's discretion — you need to request it and get their agreement."),
    ("Which is true about a 'gap year'?", ["You can take a gap year by applying for deferred entry or by applying in the gap year itself", "You can't take a gap year if you go to university", "UCAS does not allow gap years", "Gap years cancel your offers automatically"], 0, "You can either apply now for deferred entry or apply during your gap year for the next cycle."),
    ("What is the role of admissions tutors?", ["They assess applications and decide on offers for their department", "They process loans", "They run the library", "They organise sports"], 0, "Admissions tutors assess academic suitability and decide on offers for their courses."),
    ("If you are an international applicant, you must usually also show:", ["Proof of English language proficiency (e.g. IELTS, TOEFL)", "A UK driving licence", "A UK National Insurance number at application", "A UK passport"], 0, "International applicants from non-English-speaking backgrounds usually need to evidence their English ability, often via IELTS or TOEFL."),
    ("Which UK visa is used by most international students for full-time degree study?", ["Student visa (formerly Tier 4)", "Skilled Worker visa", "Family visa", "Visitor visa"], 0, "Most international students study on the UK Student visa (formerly Tier 4)."),
    ("What is a CAS in the context of international UCAS applicants?", ["Confirmation of Acceptance for Studies — issued by the university for visa purposes", "A type of personal statement", "A funding scheme", "A reference letter"], 0, "The Confirmation of Acceptance for Studies (CAS) is issued by the university and required for the Student visa application."),
    ("Roughly when do most A-level results come out in the UK?", ["Mid-August", "January", "April", "December"], 0, "A-level results are typically released in mid-August."),
    ("What happens on UCAS results day?", ["Your UCAS Hub updates with confirmation of your place or invites you into Clearing", "You receive an offer for the first time", "You sit an extra exam", "You receive your tuition fees"], 0, "On results day your status updates: if you've met your offer conditions you'll be confirmed; if not you may enter Clearing."),
    ("Which of these is NOT a typical reason to use Clearing?", ["You missed your offer conditions", "You changed your mind about your course", "You applied late (after 30 June)", "You wanted to upgrade to a higher-ranked university without conditions"], 3, "Clearing isn't generally used to 'upgrade' to a higher-ranked university — that's a different process (formerly called Adjustment / self-release into Clearing)."),
    ("'Self-release' into Clearing means:", ["You decline your firm offer to enter Clearing and look for a different course", "You release your data publicly", "You pay extra fees", "You re-take A-levels"], 0, "Self-release lets you decline your existing firm place to search Clearing for a different course."),
    ("Which of the following counts as a strong opening for a personal statement?", ["A famous quotation copied without context", "A specific reason or experience that drew you to the subject", "A complaint about your school", "A joke unrelated to the course"], 1, "A strong opening focuses on your genuine interest in the subject and is specific and original."),
    ("How should work experience be presented in a personal statement?", ["With reflection on what you learned and how it links to the course", "Just listed with dates", "Translated into another language", "As an attachment"], 0, "Universities want reflection: what you learned and how it shaped your interest, not just a list."),
    ("Which of these is good practice in writing about an extracurricular activity?", ["Briefly link it to relevant skills (teamwork, leadership, communication)", "Spend half the statement on it", "Don't mention it at all", "Pretend you led something you didn't"], 0, "Extracurriculars should be relevant and concise, focusing on transferable skills."),
    ("Which is true about Oxford and Cambridge interviews?", ["Both universities use interviews as part of their selection for most courses", "Neither interviews applicants", "Only Cambridge interviews", "Interviews are optional and rare"], 0, "Both Oxford and Cambridge interview most shortlisted applicants as a key part of selection."),
    ("Which UCAS service is for music, dance and drama performance courses at conservatoires?", ["UCAS Conservatoires", "UCAS Postgraduate", "UCAS Apprenticeships", "UCAS Hub Pro"], 0, "UCAS Conservatoires is a separate service for performance-based conservatoire courses."),
    ("Which one of these does UCAS NOT directly handle?", ["Most UK undergraduate applications", "Conservatoires applications", "Some teacher training applications", "Most postgraduate Master's applications"], 3, "Most taught postgraduate Master's applications are made directly to universities, not via UCAS."),
    ("Which service handles teacher training applications in England?", ["DfE's Apply for teacher training (via UCAS or gov.uk)", "Only UCAS Undergraduate", "Only Student Finance England", "Only HMRC"], 0, "Teacher training applications in England are made through the DfE's Apply service, which works alongside UCAS."),
    ("If you receive no offers from your 5 choices, what should you do first?", ["Immediately panic", "Use UCAS Extra to add another course one at a time", "Quit applying altogether", "Sit a new A-level"], 1, "If you have no offers, UCAS Extra lets you add additional choices for free, one at a time."),
    ("If you accept a firm offer and meet the conditions, what happens?", ["Your place is confirmed and your insurance is automatically declined", "You must accept both firm and insurance offers", "You lose your place", "You restart the application"], 0, "Meeting your firm offer's conditions confirms your place and automatically releases your insurance offer."),
    ("If you meet your insurance offer but miss your firm one, what is most likely?", ["Your insurance offer becomes your confirmed place (if conditions met)", "Both offers are cancelled", "You lose your application", "You are charged a fee"], 0, "If you miss your firm offer but meet the insurance conditions, the insurance offer becomes your confirmed place."),
    ("Which of these is true about scholarships and bursaries?", ["They are offered by individual universities and may need a separate application", "They are all automatically awarded by UCAS", "Only international students can apply", "They replace your tuition fees in full for everyone"], 0, "Scholarships and bursaries are awarded by universities and often need separate applications and eligibility criteria."),
    ("Which year of UCAS Undergraduate study is usually the first full year?", ["Year 0", "Year 1", "Year 2", "Year 3"], 1, "Year 1 is usually the first full year of study; Year 0 is a foundation year if needed."),
    ("Which of the following is a key piece of advice for choosing 5 UCAS courses?", ["Pick courses with a mix of entry requirements — some aspirational, some safer", "Pick the 5 highest-ranked universities only", "Pick courses you have no interest in for variety", "Pick all the same university"], 0, "A balanced list usually has aspirational and more realistic choices so you have options regardless of results."),
    ("'Contextual offers' usually means:", ["Offers that take into account a student's background and circumstances", "Offers based on context-free testing", "Offers that have no context", "Offers only made on results day"], 0, "Contextual offers may lower or adjust entry requirements based on factors like school performance or socioeconomic background."),
    ("Which of these is a Russell Group university?", ["University of Manchester", "There is no such group", "Only Oxford and Cambridge", "Only universities in London"], 0, "The Russell Group is an association of 24 leading UK research-intensive universities — for example, the University of Manchester."),
    ("What does 'AAB' typically mean in an A-level offer?", ["Two A grades and one B grade across three A-levels", "All A grades", "Three B grades", "Only Maths grades"], 0, "An AAB offer requires two A grades and one B in your three A-levels (or equivalent)."),
    ("Which is a normal step BEFORE submitting a UCAS Undergraduate application?", ["Researching courses and entry requirements", "Choosing your firm offer", "Applying via Clearing", "Sending original certificates"], 0, "Researching courses, entry requirements and university fit comes before you actually apply."),
    ("Which of these is NOT typically required when applying via UCAS Undergraduate?", ["Personal statement", "Reference", "Course choices", "Bank statements for the year"], 3, "Bank statements aren't part of a UCAS Undergraduate application; finance/visa processes handle those separately."),
    ("If a course says 'subject to interview' on UCAS, what does this mean?", ["You may need to attend an interview before an offer is made", "Interviews are not allowed", "You'll get an offer with no interview", "You must attend before applying"], 0, "Some courses require an interview as part of the decision-making process."),
    ("Which is true about portfolios for art and design courses?", ["You usually need to submit a portfolio in addition to the UCAS application", "Portfolios are never required", "Portfolios are submitted only on results day", "Portfolios are written in the personal statement"], 0, "Most art and design courses require a portfolio submitted directly to the university."),
    ("Which is true about UCAS personal statement formatting?", ["Bold, italics and bullet points are not preserved", "Bold and italic formatting are preserved", "You can attach images", "Hyperlinks are allowed"], 0, "Special formatting (bold, italics, bullets) and images/links aren't preserved in the UCAS personal statement."),
    ("Which fact about UCAS deadlines is true?", ["After 29 January, universities can still consider applications but have no obligation to", "After 29 January, all applications are rejected", "After 29 January, the system is closed", "After 29 January, you must apply on paper"], 0, "After the equal-consideration deadline, universities can still consider late applications but are not required to."),
    ("Which is true about taking a year out to retake A-levels?", ["You can reapply via UCAS for the next cycle with new predicted/achieved grades", "You can't reapply if you've already applied", "You must apply through Clearing only", "You must wait two years"], 0, "Resitters can reapply via UCAS the next cycle with their updated grades and a fresh application."),
    ("Which is true about UCAS reference grades?", ["The reference may include predicted grades and supporting comments", "References never mention grades", "Only employers can give grades", "Predicted grades are illegal"], 0, "References usually include predicted grades and context on the student's strengths and circumstances."),
    ("Which is NOT a valid use of the UCAS personal statement?", ["Showing motivation for the subject", "Demonstrating relevant skills and experience", "Listing every GCSE grade in detail", "Reflecting on wider reading or work experience"], 2, "GCSE grades belong in the qualifications section, not the personal statement."),
    ("Which is good advice for the structure of a personal statement?", ["Use the bulk of it to focus on academic interests and relevant skills", "Make it 50% about hobbies", "Spend half the statement on family", "Use only quotations"], 0, "Most admissions teams want to see your academic motivation and relevant skills, with extracurriculars supporting rather than dominating."),
    ("Which of these is typically true about Oxbridge applications?", ["You must apply by 15 October and may face additional tests and interviews", "The same deadlines as all other universities apply", "No personal statement is required", "Application is purely random"], 0, "Oxbridge has an earlier 15 October deadline and usually requires admissions tests and interviews."),
    ("Why is it important to read each university's specific entry requirements?", ["Requirements vary by course and may include subject prerequisites and minimum grades", "All universities have identical requirements", "They are decided at random", "Only the personal statement matters"], 0, "Entry requirements vary widely between courses and universities, including required subjects, grades and tests."),
    ("Which is true about 'minimum entry requirements' vs 'typical offers'?", ["Minimum requirements are the lowest UCAS will list; typical offers may be higher in practice", "They are always identical", "Minimum requirements are stricter than typical offers", "Typical offers don't exist"], 0, "Minimum requirements are baseline; typical or 'standard' offers can be higher depending on demand and selection."),
    ("Which is good practice when researching universities?", ["Visit open days, read course content, and check accommodation and city info", "Pick based on logo only", "Choose based on weather only", "Rely on a friend's opinion alone"], 0, "Thorough research includes course content, teaching style, facilities, location and student life."),
    ("Which is true about UCAS Conservatoires deadlines?", ["They have their own earlier deadlines for many performance courses", "They share the same deadlines as UCAS Undergraduate", "They have no deadlines", "They follow the postgraduate cycle"], 0, "Conservatoires applications often have earlier, course-specific deadlines."),
    ("Which is true about the use of AI tools in writing a personal statement?", ["UCAS guidance discourages copying AI-generated statements; similarity software may flag them", "AI-written statements are encouraged", "UCAS automatically writes them for you", "There are no rules about it"], 0, "UCAS guidance is that personal statements should be your own work; AI-generated content may trigger similarity flags."),
    ("Which of these is true about the new UCAS personal statement format being introduced (recent updates)?", ["UCAS has been moving to a structured set of questions instead of one open essay for some cycles", "It will be removed entirely", "It is being doubled to 8,000 characters", "It now requires video"], 0, "UCAS has announced structured personal statement formats with set questions to replace the single open essay for some cycles."),
    ("Which body sets tuition fee caps for English universities for home undergraduate students?", ["The UK Government / Office for Students", "UCAS", "Each university independently with no cap", "The European Union"], 0, "The UK Government sets tuition fee caps for home undergraduates in England via legislation; the Office for Students regulates."),
    ("What is the current standard tuition fee cap for English home undergraduates (approximate)?", ["£0", "Around £9,250 per year", "Around £20,000 per year", "Around £40,000 per year"], 1, "The standard tuition fee cap for English home undergraduates is around £9,250 per year (check current year)."),
    ("Which student loan covers tuition fees for English students?", ["Tuition Fee Loan from Student Finance England", "Personal bank loan only", "UCAS loan", "EU bursary"], 0, "Student Finance England provides Tuition Fee Loans paid directly to the university."),
    ("Which loan helps with living costs for English students?", ["Maintenance Loan", "Tuition Fee Loan", "UCAS Tariff Loan", "Bursary Loan"], 0, "The Maintenance Loan helps cover living costs (rent, food, travel) for English students."),
    ("Which is true about Maintenance Loans?", ["Amount depends on household income and where you study (e.g. London)", "Same for everyone", "Only for international students", "Not means-tested"], 0, "Maintenance Loans are means-tested and vary by location (London, elsewhere, parental home)."),
    ("When do you usually start repaying English student loans?", ["The April after you graduate, once income is above a threshold", "Immediately during study", "Never", "Only after age 60"], 0, "Repayments start the April after you graduate or leave the course, only when your income is above the threshold."),
    ("Which of these is true about international (non-UK) student tuition fees?", ["They are usually higher than home student fees and not capped by UK law", "They are always free", "They are always lower than home fees", "They are set by UCAS"], 0, "International fees are usually higher and not subject to UK home-fee caps."),
    ("Which of these best describes 'Office for Students' (OfS)?", ["The independent regulator of higher education in England", "An admissions service", "A student union", "A loan provider"], 0, "The OfS regulates English higher education providers, including quality and access."),
    ("Which of these would typically be a sensible 'insurance' choice?", ["A course with slightly lower entry requirements than your firm choice", "A course at the same offer as your firm choice", "A course you have no interest in", "A course you have already declined"], 0, "Insurance choices are usually courses with lower entry requirements than your firm so you have a realistic backup."),
    ("Which of these is the best summary of the UCAS journey?", ["Research → Apply (with personal statement and reference) → Receive decisions → Reply (firm/insurance) → Results → Confirmation/Clearing", "Apply → Pay → Choose graduation hat", "Sit exams → Apply later → Wait", "Get a job first → Apply later"], 0, "The standard journey is research, apply with personal statement and reference, receive decisions, reply, and confirm on results day or use Clearing."),
    ("Which is true about disabled applicants and UCAS?", ["You can declare a disability on your application to access reasonable adjustments and DSA", "You can't declare a disability", "Disclosing means automatic rejection", "Only physical disabilities are recognised"], 0, "Declaring a disability lets universities arrange reasonable adjustments and helps you access Disabled Students' Allowance (DSA)."),
    ("What is DSA?", ["Disabled Students' Allowance — extra support for students with disabilities", "Degree Studies Allowance", "Domestic Student Award", "Department of Student Affairs"], 0, "DSA = Disabled Students' Allowance, providing extra support for eligible students."),
    ("Which is true about care-experienced applicants?", ["UCAS lets you flag care-experienced status so universities can offer extra support", "There is no support available", "Care-experienced applicants are not allowed to apply", "They must apply on paper"], 0, "UCAS has a tick-box for care-experienced applicants so universities can offer targeted support like bursaries and accommodation guarantees."),
    ("Which is true about applying to multiple courses at the same university?", ["You can usually apply to more than one course at the same university (within your 5 choices)", "Never allowed", "Only one course per university is ever allowed", "Only via Extra"], 0, "You can normally apply for multiple courses at the same university within your 5-choice allocation."),
    ("Which is true about combined / joint honours degrees on UCAS?", ["They appear as a single course choice", "They use 2 of your 5 choices", "They are illegal", "They are postgraduate only"], 0, "A joint honours degree is one course choice on UCAS, even though you study two subjects."),
    ("What is the UCAS 'Buzzword' used for?", ["It identifies your school/college so the right reference is attached", "It's a marketing slogan", "It is a password for parents", "It pays the application fee"], 0, "The buzzword is a code that links your application to your school or college so they can add the reference."),
    ("Which is true about applying without a buzzword?", ["You apply as an 'independent applicant' and arrange your own reference", "You can't apply", "UCAS gives one automatically", "You must use someone else's"], 0, "Without a buzzword, you apply as an independent applicant and arrange your own reference."),
    ("Which is true about replying to offers via the UCAS Hub?", ["You typically choose one firm and (optionally) one insurance and decline the rest", "You must accept all offers", "You can hold three offers at once", "You can defer all offers automatically"], 0, "Once all decisions are in, you choose one firm and (optionally) one insurance and decline the rest."),
    ("Which is true about 'sandwich courses'?", ["They include a year in industry as part of the degree", "They are courses about food", "They are part-time only", "They are postgraduate"], 0, "Sandwich courses include a year (or longer) of work placement as part of the degree."),
    ("Which is true about 'integrated Master's' degrees (e.g. MEng, MPhys)?", ["They combine an undergraduate degree with a Master's-level final year, applied via UCAS Undergraduate", "They are postgraduate-only", "They cannot be applied to via UCAS", "They are foundation years"], 0, "Integrated Master's degrees are 4-year undergraduate-entry programmes applied for via UCAS Undergraduate."),
    ("Which is true about T Levels and UCAS?", ["T Levels carry UCAS Tariff points and are accepted by many universities", "T Levels are not recognised at all", "T Levels are foreign qualifications", "T Levels are only for apprenticeships"], 0, "T Levels are technical post-16 qualifications that carry UCAS Tariff points and are accepted by many universities."),
    ("Which is true about Access to HE Diplomas?", ["They are designed for mature students to progress to university and carry UCAS Tariff points", "They are GCSEs", "They cannot be used for university entry", "They are only for STEM"], 0, "Access to HE Diplomas help mature students access university and carry UCAS Tariff points."),
    ("Which best describes 'transferring' to another university after starting?", ["It's possible in some cases but you need to apply and discuss with both universities; not handled by UCAS Undergraduate as a transfer service", "UCAS automatically transfers you", "Transferring is impossible in the UK", "Transferring requires re-applying via Clearing only"], 0, "Transfers are arranged directly with the new university (and sometimes the old one); UCAS Undergraduate isn't a transfer system."),
    ("Which is the best description of UCAS overall?", ["A central admissions service that streamlines UK university applications and matches applicants with courses and places", "A loan provider", "A subscription service for students", "A government department"], 0, "UCAS is a central admissions service used by most UK universities and colleges for undergraduate (and some other) applications."),
]

assert len(RAW) >= 24, "Need at least 24 questions"

bank = []
for i, (q, opts, ans, expl) in enumerate(RAW, 1):
    bank.append({
        "id": f"ucas-mc-{i:04d}",
        "type": "multiple_choice",
        "question": q,
        "options": opts,
        "correctAnswer": ans,
        "explanation": expl,
    })

# Build 45 mocks of 24 unique questions each via round-robin
N = len(bank)
mocks = []
for m in range(45):
    start = (m * 24) % N
    ids = []
    used = set()
    i = 0
    while len(ids) < 24:
        idx = (start + i) % N
        qid = bank[idx]["id"]
        if qid not in used:
            ids.append(qid)
            used.add(qid)
        i += 1
        if i > N * 2:
            break
    mocks.append({
        "mockNumber": m + 1,
        "title": f"UCAS Application Knowledge Test {m + 1}",
        "questionIds": ids,
    })

data = {
    "version": 2,
    "topic": "ucas-application-knowledge",
    "bank": bank,
    "mocks": mocks,
}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2))
print(f"Wrote {OUT} — bank={len(bank)} mocks={len(mocks)} each with {len(mocks[0]['questionIds'])} questions")
