#!/usr/bin/env python3
"""Generate public/mocks/workplace-health-safety-awareness.json (v2, 45 mocks × 24 Qs)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "mocks" / "workplace-health-safety-awareness.json"

RAW = [
    ("Which UK Act is the foundation of workplace health and safety law?", ["Health and Safety at Work etc. Act 1974", "Workplace Safety Act 1992", "Employment Rights Act 1996", "Factory Act 1961"], 0, "The Health and Safety at Work etc. Act 1974 (HSWA) is the primary piece of UK legislation covering workplace health and safety."),
    ("Who has a duty to ensure, so far as is reasonably practicable, the health and safety of employees at work?", ["The employer", "Only the safety officer", "Only the employees", "Only HSE inspectors"], 0, "Section 2 of HSWA places a duty on every employer to ensure the H&S of their employees so far as is reasonably practicable."),
    ("What does 'so far as is reasonably practicable' mean?", ["Weighing risk against the cost, time and effort to control it", "Doing nothing at all", "Eliminating every risk regardless of cost", "Only acting if an accident happens"], 0, "It means balancing the level of risk against the resources (money, time, trouble) needed to control it."),
    ("Which body enforces health and safety law in most UK workplaces?", ["HSE (Health and Safety Executive)", "DVLA", "DVSA", "Ofsted"], 0, "The HSE is the main UK regulator for workplace health and safety, alongside local authorities for some sectors."),
    ("What does RIDDOR stand for?", ["Reporting of Injuries, Diseases and Dangerous Occurrences Regulations", "Regulation of Industrial Damage and Dangerous Occurrences Rules", "Rapid Incident Disclosure Reporting Rules", "Reporting of Injuries, Damage, Dust and Operational Risks"], 0, "RIDDOR = Reporting of Injuries, Diseases and Dangerous Occurrences Regulations 2013."),
    ("Under RIDDOR, which of these must be reported?", ["A specified injury such as a fractured arm", "A paper cut", "A trip with no injury", "A near miss with no consequence"], 0, "RIDDOR requires specified injuries (e.g. fractures other than fingers/toes), over-7-day absences and dangerous occurrences to be reported."),
    ("How long can an employee be off work due to a work-related injury before it becomes reportable under RIDDOR?", ["More than 3 consecutive days", "More than 7 consecutive days (not counting the day of the incident)", "More than 14 days", "More than 28 days"], 1, "Over-7-day incapacitation injuries are reportable under RIDDOR."),
    ("What does COSHH stand for?", ["Control of Substances Hazardous to Health", "Care of Safety Standards in Health", "Code of Safe Health Handling", "Containment of Substances and Hazardous Handling"], 0, "COSHH = Control of Substances Hazardous to Health Regulations 2002."),
    ("Which is the FIRST step of a risk assessment under the Management of Health and Safety at Work Regulations 1999?", ["Identify the hazards", "Buy PPE", "Write a method statement", "Issue a permit to work"], 0, "Step 1 of the HSE 5-step model is to identify the hazards."),
    ("How many steps does the HSE's standard risk assessment model have?", ["3", "4", "5", "7"], 2, "HSE describes a 5-step model: identify hazards, decide who could be harmed, evaluate risks and controls, record findings, review."),
    ("What is the difference between a hazard and a risk?", ["A hazard has the potential to cause harm; a risk is the likelihood and severity of that harm occurring", "They are the same thing", "A risk is always physical, a hazard is always chemical", "A hazard is only legal terminology"], 0, "A hazard is anything with potential to cause harm; risk is the likelihood combined with severity."),
    ("Which is the highest in the hierarchy of control measures?", ["Eliminate the hazard", "Use PPE", "Issue safety signs", "Train staff"], 0, "Elimination is the most effective control; PPE is the last line of defence."),
    ("Where does PPE sit in the hierarchy of control?", ["At the top — used first", "In the middle — equal to engineering controls", "At the bottom — last resort after other controls", "PPE is not part of the hierarchy"], 2, "PPE is the lowest tier in the hierarchy and should be used only when higher controls cannot adequately reduce the risk."),
    ("Who pays for PPE that is required for work?", ["The employer, free of charge to employees", "The employee", "The HSE", "Split 50/50"], 0, "Under PPE at Work Regulations 1992, employers must provide suitable PPE free of charge."),
    ("Which Regulations cover manual handling at work?", ["Manual Handling Operations Regulations 1992", "Lifting Operations Regulations 2002", "Working Time Regulations 1998", "Provision of Work Equipment Regulations 1998"], 0, "Manual Handling Operations Regulations 1992 (as amended) govern manual handling tasks."),
    ("What is the FIRST consideration when there's a risk from manual handling?", ["Avoid the manual handling task if reasonably practicable", "Wear gloves", "Use a back belt", "Lift quickly"], 0, "MHOR follows: avoid → assess → reduce — start by avoiding the task where reasonably practicable."),
    ("Which body part is most commonly injured by poor manual handling?", ["The back, especially the lower back", "The feet", "The eyes", "The teeth"], 0, "Lower-back injuries account for the largest share of manual handling injuries."),
    ("Which is the correct technique for lifting a load from the floor?", ["Bend the knees, keep the back straight, hold the load close to the body", "Bend the back, keep the knees straight", "Twist while lifting", "Lift with arms fully extended"], 0, "Good lifting technique = stable stance, knees bent, back straight, load close to the centre of the body, no twisting."),
    ("Which colour usually indicates a 'prohibition' safety sign?", ["Red circle with diagonal bar on white background", "Yellow triangle", "Blue circle", "Green square"], 0, "Prohibition signs are round, red and white with a diagonal bar — e.g. 'No smoking'."),
    ("Which colour and shape is used for warning safety signs?", ["Yellow triangle with black border", "Blue circle", "Red circle", "Green square"], 0, "Warning signs are yellow triangles with a black border."),
    ("Which colour and shape is used for mandatory safety signs (you must do)?", ["Blue circle", "Red circle", "Yellow triangle", "Green square"], 0, "Mandatory signs are blue circles — e.g. 'Wear ear protection'."),
    ("Which colour is used for safe condition signs (e.g. fire exit)?", ["Green", "Red", "Blue", "Yellow"], 0, "Safe condition signs are green and rectangular — e.g. fire exit, first aid."),
    ("What does the fire triangle consist of?", ["Heat, fuel, oxygen", "Smoke, water, dust", "Wood, paper, plastic", "Sparks, flames, alarms"], 0, "Fire needs heat, fuel and oxygen — remove any one to extinguish."),
    ("Which fire extinguisher class is suitable for electrical fires?", ["CO2 (carbon dioxide)", "Water", "Foam", "Wet chemical"], 0, "CO2 is safe on live electrical equipment; water and foam conduct electricity."),
    ("Which fire extinguisher is best for cooking oil/fat fires?", ["Wet chemical", "Water", "CO2", "Powder"], 0, "Class F (cooking oils and fats) fires are tackled with wet chemical extinguishers."),
    ("What should you do FIRST if you discover a fire at work?", ["Raise the alarm", "Try to extinguish it before telling anyone", "Finish your task", "Take a photo for the report"], 0, "Always raise the alarm first so people can evacuate."),
    ("On hearing the fire alarm, you should:", ["Leave by the nearest safe exit and go to the assembly point", "Collect your belongings first", "Use the lift", "Hide under your desk"], 0, "Evacuate via the nearest safe exit, use stairs (not lifts) and go straight to the assembly point."),
    ("Why must you not use the lifts during a fire alarm?", ["They can fail, fill with smoke or strand people", "They are too slow", "They cost too much to operate", "They are reserved for managers"], 0, "Lifts can lose power, trap occupants and act as a chimney for smoke and heat."),
    ("Which Regulations cover the use of display screen equipment (DSE)?", ["Health and Safety (Display Screen Equipment) Regulations 1992", "Workplace Regulations 1992", "Office Health Act 2005", "DSE Act 2008"], 0, "The DSE Regulations 1992 (as amended) cover habitual computer users."),
    ("Under DSE Regulations, who is entitled to a free eye test paid for by the employer?", ["DSE users (employees who use display screens as a significant part of their normal work)", "Only office managers", "Only IT staff", "Anyone, regardless of role"], 0, "DSE users can request an eye test paid for by the employer."),
    ("What is the recommended approach to long DSE sessions?", ["Take short, frequent breaks away from the screen", "Work non-stop for 8 hours", "Use one long lunch break only", "Skip breaks to finish early"], 0, "Short, frequent breaks reduce eyestrain and musculoskeletal strain — far better than one long break."),
    ("Which Regulations require workplaces to have suitable welfare facilities (toilets, drinking water, rest areas)?", ["Workplace (Health, Safety and Welfare) Regulations 1992", "Welfare Act 1968", "HSWA 1974 directly", "Public Health Act 1875"], 0, "These regulations cover basic welfare facilities, temperature, lighting, ventilation and cleanliness."),
    ("What is the minimum recommended workplace temperature for indoor sedentary work in the UK?", ["At least 16°C", "At least 10°C", "At least 25°C", "There is no recommendation"], 0, "HSE recommends a minimum of 16°C for sedentary indoor work (13°C for physical work)."),
    ("Who must complete the accident book entry for a workplace injury?", ["The injured person or someone acting on their behalf", "Only the HR director", "Only an HSE inspector", "Only the fire warden"], 0, "Entries can be made by the injured person or by someone on their behalf — and must respect data protection."),
    ("Why must accident book entries be removed and stored separately once completed?", ["Data protection — they contain personal information", "To save space", "To hide them from staff", "Because of fire risk"], 0, "Completed pages must be removed and stored securely to comply with UK GDPR/Data Protection."),
    ("Which document explains how a specific task should be done safely?", ["A safe system of work / method statement", "An invoice", "An organisational chart", "A delivery note"], 0, "A safe system of work (often supported by a method statement) sets out how to do a task safely."),
    ("What is a 'near miss'?", ["An incident that could have caused injury or damage but didn't", "An injury requiring hospital treatment", "A fatal accident", "A reportable disease"], 0, "A near miss is an unplanned event that didn't result in injury or damage but had the potential to."),
    ("Why are near misses important?", ["They highlight underlying hazards before someone is hurt", "They never need recording", "They prove staff are careless", "They reduce insurance premiums automatically"], 0, "Investigating near misses helps prevent future accidents — they are leading indicators."),
    ("Which of these is the correct order of priority in the fire safety hierarchy?", ["Prevent → detect → alert → evacuate → fight (only if trained and safe)", "Fight → alert → evacuate", "Evacuate → ignore alarms", "Detect → ignore → carry on"], 0, "Prevent ignition, detect quickly, alert occupants, evacuate, and only tackle if trained and safe."),
    ("Which Regulations cover the safe use of work equipment such as power tools and machinery?", ["PUWER 1998 — Provision and Use of Work Equipment Regulations", "WAH 2005", "LOLER 1998", "RIDDOR 2013"], 0, "PUWER 1998 covers the safe selection, use, inspection and maintenance of work equipment."),
    ("Which Regulations cover lifting equipment and lifting operations?", ["LOLER 1998", "PUWER 1998", "MHOR 1992", "WAH 2005"], 0, "LOLER 1998 — Lifting Operations and Lifting Equipment Regulations — covers cranes, hoists, lifts and slings."),
    ("Which Regulations cover work at height?", ["The Work at Height Regulations 2005", "HSWA 1974 only", "PUWER 1998", "LOLER 1998"], 0, "The Work at Height Regulations 2005 require height work to be properly planned, supervised and carried out safely."),
    ("Which is the FIRST priority when planning work at height?", ["Avoid working at height if reasonably practicable", "Buy a harness", "Issue a permit", "Use a ladder"], 0, "Avoid → prevent → minimise — start by avoiding the need to work at height where possible."),
    ("Which Regulations protect against the risks of asbestos?", ["Control of Asbestos Regulations 2012", "COSHH 2002 only", "PUWER 1998", "HSWA 1974 only"], 0, "Control of Asbestos Regulations 2012 (CAR 2012) place specific duties on duty-holders and employers."),
    ("If you suspect a material contains asbestos, you should:", ["Stop work, leave the area undisturbed and report to your supervisor immediately", "Sand it down to check", "Drill into it to confirm", "Throw it in the skip"], 0, "Suspected ACMs (asbestos-containing materials) must not be disturbed — stop work and report."),
    ("What is the duty under HSWA section 7 placed on employees?", ["Take reasonable care for their own and others' health and safety, and cooperate with the employer", "Pay for their own PPE", "Ignore safety procedures if busy", "Report only fatal incidents"], 0, "Section 7 requires employees to take reasonable care and cooperate with H&S arrangements."),
    ("Can an employee be prosecuted personally for a serious breach of health and safety law?", ["Yes — employees can be prosecuted under sections 7 and 8 of HSWA", "No — only employers can be prosecuted", "Only HSE inspectors face prosecution", "Only directors face prosecution"], 0, "Both employees and employers can be prosecuted for serious breaches."),
    ("Which Regulations require employers to consult employees on H&S matters?", ["Safety Representatives and Safety Committees Regulations 1977 and the H&S (Consultation with Employees) Regulations 1996", "HSWA only", "PUWER only", "RIDDOR only"], 0, "Either union-appointed safety representatives or directly-elected representatives of employee safety must be consulted."),
    ("What is the maximum noise exposure level (lower exposure action value) before action is required under the Control of Noise at Work Regulations 2005?", ["80 dB(A) daily/weekly average", "120 dB(A)", "60 dB(A)", "100 dB(A)"], 0, "Lower action value = 80 dB(A); upper action value = 85 dB(A); exposure limit = 87 dB(A)."),
    ("What is the upper exposure action value for noise under the 2005 Regulations?", ["85 dB(A)", "60 dB(A)", "70 dB(A)", "100 dB(A)"], 0, "At 85 dB(A) employers must provide hearing protection and create hearing protection zones."),
    ("Which type of PPE protects against airborne dust and harmful particles?", ["A correctly fitted RPE / respirator with the right filter", "Latex gloves", "Steel toecap boots", "Hi-vis vest"], 0, "Respiratory Protective Equipment (RPE) — selected after a face-fit test for tight-fitting masks — protects the lungs."),
    ("Why is face-fit testing important for tight-fitting respirators?", ["A poor fit lets contaminated air leak in around the seal", "It's a legal formality only", "It improves comfort only", "It changes the mask's colour"], 0, "If the seal isn't tight, contaminated air bypasses the filter — making the RPE useless."),
    ("What does a SDS (Safety Data Sheet) tell you?", ["The hazards, safe handling, storage and emergency information for a chemical", "The price of the chemical", "The history of the manufacturer", "The marketing slogan"], 0, "Safety Data Sheets must be supplied with hazardous chemicals and underpin COSHH assessments."),
    ("Which is the safest way to store flammable liquids on site?", ["In a designated, ventilated and bunded flammable store, away from ignition sources", "Next to the boiler", "Under the kitchen sink with food", "In an open bucket on the shop floor"], 0, "Flammables must be stored in suitable cabinets/stores with ventilation, segregation and away from ignition."),
    ("Which is the safest electrical safety practice?", ["Use portable appliance testing (PAT) and visual checks; isolate before maintenance", "Repair live equipment", "Run cables across walkways", "Overload sockets with adapters"], 0, "Visual inspections, PAT (where appropriate), proper isolation and avoiding trip hazards keep electrical work safe."),
    ("What does LOTO stand for in electrical and machinery safety?", ["Lockout / Tagout — isolating energy sources before work", "Lift Or Take Out", "Load On Top Off", "Low Operation Tag Out"], 0, "LOTO is the procedure to isolate energy and prevent unexpected re-energisation during maintenance."),
    ("Which document allows specific high-risk work to proceed only after authorisation and controls?", ["A permit to work", "A purchase order", "A timesheet", "A delivery note"], 0, "A permit to work is a formal authorisation used for high-risk activities (hot work, confined spaces, etc.)."),
    ("What is the safest approach to entering a confined space?", ["Avoid entry if possible; if not, use a permit, atmosphere testing, trained personnel and rescue plan", "Send one person in alone", "Test the air after entering", "Leave the entry hatch unattended"], 0, "Confined Spaces Regulations 1997 — avoid entry, plan, train, test atmosphere, have rescue arrangements."),
    ("Why is good housekeeping important on a worksite?", ["It reduces slips, trips, fire load and fall hazards", "It only makes the place look tidy", "It is just a cosmetic concern", "It is irrelevant to safety"], 0, "Poor housekeeping is one of the most common causes of workplace injuries."),
    ("Which is the leading cause of workplace injury in UK offices and shops?", ["Slips, trips and falls on the same level", "Falls from cranes", "Asbestos exposure", "Lightning strikes"], 0, "Slips and trips consistently cause the largest share of non-fatal workplace injuries."),
    ("What should you do if a floor is wet?", ["Display a wet floor sign and dry/clean promptly; restrict access if necessary", "Ignore it", "Tell the next visitor verbally only", "Cover with newspaper"], 0, "Visible warning signs and prompt cleaning are essential to manage slip risks."),
    ("Which is a typical 'specified injury' under RIDDOR?", ["Fracture (other than to fingers, thumbs or toes)", "A bruise", "A common cold caught at work", "Tiredness"], 0, "RIDDOR specified injuries include serious fractures, amputations, serious burns and loss of consciousness."),
    ("How quickly must a dangerous occurrence be reported under RIDDOR?", ["Without delay (usually within 10 days, online via HSE)", "Within a year", "Within 5 years", "It never needs reporting"], 0, "Dangerous occurrences must be reported online to HSE without delay and within 10 days."),
    ("Which is a duty of an employer to non-employees (visitors, contractors, public)?", ["Conduct undertaking so they are not exposed to H&S risks, so far as reasonably practicable (HSWA s.3)", "No duty exists", "Only insurance is needed", "Only signage is needed"], 0, "Section 3 of HSWA extends duties to non-employees affected by the employer's undertaking."),
    ("What does HSE stand for?", ["Health and Safety Executive", "Health Sector Examinations", "Hazardous Substances Enforcement", "Home Safety Executive"], 0, "HSE = Health and Safety Executive, the GB regulator for workplace H&S."),
    ("Which is the correct definition of an 'accident' in H&S terminology?", ["An unplanned event that resulted in injury, ill-health or damage", "Any planned activity", "A meeting that ran over time", "A successful project"], 0, "An accident is an unplanned event causing harm; near misses are events with potential but no outcome."),
    ("Which inspection rights do HSE inspectors have under HSWA?", ["Enter premises, take measurements/samples, require information and issue improvement or prohibition notices", "Only enter with permission", "Only inspect once a year", "Only inspect after an accident"], 0, "Inspectors have wide powers including entry without notice, sampling, and serving improvement/prohibition notices."),
    ("What is the difference between an improvement notice and a prohibition notice?", ["Improvement = fix a breach by a set date; prohibition = stop the activity immediately as it carries serious risk", "There is no difference", "Both mean the business closes", "Prohibition is less serious than improvement"], 0, "Improvement notices require remedial action by a deadline; prohibition notices stop activity creating a risk of serious personal injury."),
    ("If you spot a serious hazard at work, what should you do FIRST?", ["Make the area safe if possible and report it to your supervisor / safety representative", "Ignore it — it's not your job", "Take a photo and post on social media", "Wait until next week's meeting"], 0, "Make it safe (or isolate) if you can do so safely, then report through the proper channels."),
    ("Why do employers need a written H&S policy?", ["Legally required if you employ 5 or more people; sets out the policy, organisation and arrangements", "Only multinationals need one", "Only the public sector needs one", "It is optional regardless of size"], 0, "Employers with 5 or more employees must have a written H&S policy under HSWA."),
    ("What information must be displayed on the HSE 'Health and Safety Law' poster (or equivalent leaflet)?", ["Basic outline of H&S law and contact details for the responsible person and enforcing authority", "Only the staff handbook", "Only fire exit information", "Only the company's profits"], 0, "The HSE Law poster (or leaflet) outlines workers' and employers' duties and must be displayed/issued."),
    ("Which symbol denotes a flammable substance under the GHS/CLP labelling system?", ["A flame in a red diamond", "A skull and crossbones", "A green cross", "A blue circle"], 0, "GHS/CLP uses red diamond pictograms — flame indicates flammable hazards."),
    ("Which GHS pictogram indicates serious health hazards (e.g. carcinogenic, mutagenic)?", ["Health hazard (silhouette of a person with a star burst on the chest)", "Flame", "Exclamation mark", "Skull and crossbones"], 0, "The 'health hazard' pictogram (CHEM-MAN figure) covers carcinogens, mutagens, reproductive toxins, respiratory sensitisers and STOTs."),
    ("Which GHS pictogram indicates a corrosive substance?", ["A test tube pouring onto a surface and a hand showing damage", "A flame", "A green cross", "A blue circle"], 0, "The corrosion pictogram shows substances that cause skin burns, eye damage or metal corrosion."),
    ("If chemicals splash in your eye, what is the FIRST aid action?", ["Irrigate the eye with clean water for at least 10–15 minutes and seek medical help", "Rub the eye to remove the chemical", "Apply ointment immediately", "Wait to see if it stings"], 0, "Immediate, prolonged irrigation with clean water minimises damage; then seek medical help."),
    ("How many first aiders does a workplace need?", ["Determined by a first-aid needs assessment considering risk, numbers, layout and travel times", "Always exactly 1", "Always exactly 10", "Not required at all"], 0, "There is no fixed number — employers must assess first-aid needs under the Health and Safety (First-Aid) Regulations 1981."),
    ("Which Regulations cover the provision of first aid at work?", ["Health and Safety (First-Aid) Regulations 1981", "HSWA only", "PUWER only", "LOLER only"], 0, "These regulations require employers to provide adequate first-aid equipment, facilities and personnel."),
    ("Which of these is NOT typically a contents item of a workplace first-aid kit?", ["Prescription medication", "Plasters", "Sterile dressings", "Disposable gloves"], 0, "HSE first-aid kits should not contain medication; they hold dressings, plasters, gloves, eye pads, etc."),
    ("Which is the correct compression rate for adult CPR?", ["100 to 120 compressions per minute", "30 per minute", "60 per minute", "200 per minute"], 0, "Adult CPR guidelines specify 100–120 compressions per minute at a depth of 5–6cm."),
    ("What does AED stand for?", ["Automated External Defibrillator", "Adult Emergency Device", "Automatic Eye Dropper", "Advanced Electric Diagnostic"], 0, "AED = Automated External Defibrillator, used to treat cardiac arrest."),
    ("Which sign in green and white commonly indicates first aid?", ["White cross on a green square or rectangle", "Red circle", "Blue triangle", "Yellow diamond"], 0, "Safe condition (green) signs include first aid (white cross) and emergency exits."),
    ("What is the recovery position used for?", ["An unconscious casualty who is breathing normally to keep their airway clear", "An alert casualty who is talking", "Cardiac arrest", "Heavy bleeding only"], 0, "The recovery position is used for an unconscious, breathing casualty to maintain the airway."),
    ("When should you call 999 / 112 for an emergency at work?", ["For serious injuries, breathing difficulties, suspected stroke/heart attack or any life-threatening situation", "Only after the manager arrives", "Never — call HR first", "Only if a first aider isn't around"], 0, "For life-threatening emergencies always call emergency services immediately."),
    ("Which is the safest approach to lone working?", ["A lone-worker risk assessment with check-in systems and emergency procedures", "Hope for the best", "Ban communication during shifts", "Lock the doors"], 0, "Lone workers must be specifically risk-assessed with effective communication and emergency arrangements."),
    ("What is workplace bullying or harassment usually addressed under?", ["Equality Act 2010 and employer H&S duties (stress is an H&S risk)", "HSWA only", "Only criminal law", "Only HR policy with no legal basis"], 0, "Bullying/harassment can breach the Equality Act 2010 and create H&S risks (work-related stress) under HSWA."),
    ("Which is true about work-related stress?", ["Employers must assess and control it like any other H&S risk", "It is not a workplace issue", "It only applies to managers", "It is only the GP's responsibility"], 0, "HSE Management Standards treat stress as a workplace H&S issue requiring assessment and control."),
    ("Which type of vehicle workplace activity has its own ACOP and guidance?", ["Workplace transport — forklifts, vans and reversing vehicles", "Only HGVs on motorways", "Only racing cars", "Only emergency vehicles"], 0, "HSE has specific guidance on workplace transport, including reversing, separation of pedestrians and FLT operations."),
    ("Why should pedestrians and vehicles be segregated on site?", ["To prevent collisions which are a major cause of workplace fatalities", "Only for aesthetics", "To save fuel", "To reduce car park fees"], 0, "Separating pedestrians and vehicles using barriers, marked walkways and signs reduces collision risk."),
    ("Which young person at work needs special H&S consideration?", ["Anyone under 18 — risk assessment must take account of inexperience and immaturity", "Only those under 14", "Only apprentices over 21", "Only volunteers"], 0, "Specific duties apply to under-18s; risk assessments must consider inexperience and competence."),
    ("Which of the following is correct about the H&S of new and expectant mothers?", ["Employers must assess risks and adjust work or hours where necessary", "Pregnancy is not a workplace consideration", "No risk assessment is needed", "Only the GP decides"], 0, "Specific risk assessment is required for new and expectant mothers under MHSWR 1999."),
    ("Which is true about contractors working on site?", ["The employer must cooperate, share H&S information and ensure contractors are competent", "The employer has no duties to contractors", "Only the contractor's manager is responsible", "Contractors can ignore site rules"], 0, "Duties of cooperation, information sharing and ensuring competence apply (CDM and HSWA)."),
    ("Which Regulations cover construction projects in the UK?", ["Construction (Design and Management) Regulations 2015 (CDM 2015)", "PUWER 1998 only", "LOLER 1998 only", "RIDDOR 2013 only"], 0, "CDM 2015 sets duties for clients, designers, principal designers, principal contractors, contractors and workers."),
    ("What is the goal of induction training for new staff?", ["Cover site rules, hazards, emergency procedures and reporting before work begins", "Sell company merchandise", "Discuss salary", "Only show the canteen"], 0, "Induction must cover site-specific H&S so new starters work safely from day one."),
    ("Which is true about toolbox talks?", ["Short, focused talks on specific H&S topics, often used on construction sites", "Long lectures of an hour or more", "Only for managers", "Optional with no legal value"], 0, "Toolbox talks reinforce specific H&S topics and demonstrate ongoing consultation and training."),
    ("If you don't know how to do a task safely, what should you do?", ["Stop and ask your supervisor for instruction and training", "Guess and continue", "Ask a member of the public", "Skip the task and don't tell anyone"], 0, "Never proceed without competence; section 7 of HSWA requires employees to cooperate and not put themselves or others at risk."),
    ("Which of these is the most accurate statement about workplace H&S?", ["Everyone in the workplace has a role in health and safety, not just managers", "Only the safety officer is responsible", "Only the HSE is responsible", "Only the cleaners are responsible"], 0, "H&S is a shared responsibility from board level to the newest employee."),
    ("Which Regulations specifically govern the safe handling of vibration risks (e.g. from power tools)?", ["Control of Vibration at Work Regulations 2005", "PUWER 1998 only", "RIDDOR 2013", "HSWA 1974 only"], 0, "The Control of Vibration at Work Regulations 2005 set daily exposure action and limit values for hand-arm and whole-body vibration."),
    ("What is HAVS?", ["Hand-Arm Vibration Syndrome — a painful, sometimes disabling condition caused by prolonged exposure to vibration", "Hazardous Air Ventilation System", "Health and Vehicle Safety", "Heavy-Asset Vibration Standard"], 0, "HAVS can cause numbness, tingling, loss of grip and vibration white finger; it's preventable through controls and exposure limits."),
    ("Which legal document allows employees to refuse to undertake work they reasonably believe is unsafe?", ["Employment Rights Act 1996 (protection from detriment) combined with HSWA principles", "HSWA only", "PUWER only", "RIDDOR only"], 0, "Employees have legal protection from detriment for leaving or refusing to work in serious and imminent danger."),
    ("Which is true about safety committees?", ["Required to be set up if requested in writing by two or more safety representatives", "Always voluntary with no legal basis", "Only for fire wardens", "Only annual events"], 0, "Under the Safety Representatives and Safety Committees Regulations 1977, a committee must be set up on a written request from two or more representatives."),
    ("What is the role of a 'competent person' in H&S management?", ["Someone with the skills, knowledge and experience to identify hazards and advise on controls", "Anyone, regardless of training", "Only the CEO", "Only an HSE inspector"], 0, "Employers must appoint one or more competent persons to help comply with H&S law (MHSWR 1999, reg 7)."),
    ("Which is the correct attitude toward H&S 'shortcuts' on a routine task?", ["Don't take them — most accidents happen during familiar tasks where complacency sets in", "Always take them to save time", "Only take them at the end of the day", "Encourage them to boost productivity"], 0, "Complacency is a leading cause of accidents; following the safe system of work matters even on routine jobs."),
    ("How often should risk assessments be reviewed?", ["Whenever circumstances change, after incidents, or at regular planned intervals", "Only every 10 years", "Never once written", "Only if HSE asks"], 0, "MHSWR 1999 requires review whenever there is reason to suspect they are no longer valid or there has been a significant change."),
    ("Which is true about safety culture?", ["It reflects shared values, attitudes and behaviours toward safety at every level", "It only matters in factories", "It is the responsibility of HR alone", "It is only relevant after a serious accident"], 0, "A strong safety culture is associated with fewer accidents and is built through leadership, training and consultation."),
    ("Which of the following best describes 'duty of care' at work?", ["A legal and moral duty to take reasonable steps to prevent harm to others", "An optional courtesy", "Only owed by employers", "Only owed to customers"], 0, "Duty of care is the cornerstone of H&S — owed by employers, employees and contractors to each other and to the public."),
    ("Which of the following is the BEST summary of effective workplace H&S?", ["Plan → Do → Check → Act — continuously improving controls based on assessment and review", "Wait for accidents to happen → react", "Buy PPE → assume it's enough", "Train once → never review"], 0, "HSE's PDCA cycle (HSG65 'Managing for health and safety') is the recognised approach to continual improvement."),
]

assert len(RAW) >= 24, "Need at least 24 questions"

bank = []
for i, (q, opts, ans, expl) in enumerate(RAW, 1):
    bank.append({
        "id": f"whs-mc-{i:04d}",
        "type": "multiple_choice",
        "question": q,
        "options": opts,
        "correctAnswer": ans,
        "explanation": expl,
    })

N = len(bank)
mocks = []
for m in range(45):
    start = (m * 24) % N
    ids = []
    used = set()
    i = 0
    while len(ids) < 24:
        idx = (start + i) % N
        qid = bank[idx]["id"]
        if qid not in used:
            ids.append(qid)
            used.add(qid)
        i += 1
        if i > N * 2:
            break
    mocks.append({
        "mockNumber": m + 1,
        "title": f"Workplace Health & Safety Awareness Test {m + 1}",
        "questionIds": ids,
    })

data = {
    "version": 2,
    "topic": "workplace-health-safety-awareness",
    "bank": bank,
    "mocks": mocks,
}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2))
print(f"Wrote {OUT} — bank={len(bank)} mocks={len(mocks)} each with {len(mocks[0]['questionIds'])} questions")
