/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SeruTflRouteImport } from './routes/seru-tfl'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExamUpdatesRouteImport } from './routes/exam-updates'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AllTestsRouteImport } from './routes/all-tests'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminKb20IndexRouteImport } from './routes/admin-kb20.index'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'
import { Route as GuideSlugRouteImport } from './routes/guide.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminKb20UsersRouteImport } from './routes/admin-kb20.users'
import { Route as AdminKb20LoginRouteImport } from './routes/admin-kb20.login'
import { Route as AdminKb20DiagnosticsRouteImport } from './routes/admin-kb20.diagnostics'
import { Route as AdminKb20QuestionsIndexRouteImport } from './routes/admin-kb20.questions.index'
import { Route as AdminKb20QuestionsTopicRouteImport } from './routes/admin-kb20.questions.$topic'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SeruTflRoute = SeruTflRouteImport.update({
  id: '/seru-tfl',
  path: '/seru-tfl',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamUpdatesRoute = ExamUpdatesRouteImport.update({
  id: '/exam-updates',
  path: '/exam-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AllTestsRoute = AllTestsRouteImport.update({
  id: '/all-tests',
  path: '/all-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminKb20IndexRoute = AdminKb20IndexRouteImport.update({
  id: '/admin-kb20/',
  path: '/admin-kb20/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/guide/$slug',
  path: '/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminKb20UsersRoute = AdminKb20UsersRouteImport.update({
  id: '/admin-kb20/users',
  path: '/admin-kb20/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKb20LoginRoute = AdminKb20LoginRouteImport.update({
  id: '/admin-kb20/login',
  path: '/admin-kb20/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKb20DiagnosticsRoute = AdminKb20DiagnosticsRouteImport.update({
  id: '/admin-kb20/diagnostics',
  path: '/admin-kb20/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKb20QuestionsIndexRoute = AdminKb20QuestionsIndexRouteImport.update({
  id: '/admin-kb20/questions/',
  path: '/admin-kb20/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKb20QuestionsTopicRoute = AdminKb20QuestionsTopicRouteImport.update({
  id: '/admin-kb20/questions/$topic',
  path: '/admin-kb20/questions/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/all-tests': typeof AllTestsRoute
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/exam-updates': typeof ExamUpdatesRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seru-tfl': typeof SeruTflRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin-kb20/diagnostics': typeof AdminKb20DiagnosticsRoute
  '/admin-kb20/login': typeof AdminKb20LoginRoute
  '/admin-kb20/users': typeof AdminKb20UsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin-kb20/': typeof AdminKb20IndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin-kb20/questions/$topic': typeof AdminKb20QuestionsTopicRoute
  '/admin-kb20/questions/': typeof AdminKb20QuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/all-tests': typeof AllTestsRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/exam-updates': typeof ExamUpdatesRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seru-tfl': typeof SeruTflRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin-kb20/diagnostics': typeof AdminKb20DiagnosticsRoute
  '/admin-kb20/login': typeof AdminKb20LoginRoute
  '/admin-kb20/users': typeof AdminKb20UsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin-kb20': typeof AdminKb20IndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin-kb20/questions/$topic': typeof AdminKb20QuestionsTopicRoute
  '/admin-kb20/questions': typeof AdminKb20QuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/all-tests': typeof AllTestsRoute
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/exam-updates': typeof ExamUpdatesRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seru-tfl': typeof SeruTflRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin-kb20/diagnostics': typeof AdminKb20DiagnosticsRoute
  '/admin-kb20/login': typeof AdminKb20LoginRoute
  '/admin-kb20/users': typeof AdminKb20UsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/quiz/$slug': typeof QuizSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/admin-kb20/': typeof AdminKb20IndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin-kb20/questions/$topic': typeof AdminKb20QuestionsTopicRoute
  '/admin-kb20/questions/': typeof AdminKb20QuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/all-tests'
    | '/blog'
    | '/bookmarks'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/exam-updates'
    | '/faq'
    | '/feedback'
    | '/forgot-password'
    | '/help'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/robots.txt'
    | '/seru-tfl'
    | '/signin'
    | '/signup'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/admin-kb20/diagnostics'
    | '/admin-kb20/login'
    | '/admin-kb20/users'
    | '/blog/$slug'
    | '/category/$slug'
    | '/guide/$slug'
    | '/quiz/$slug'
    | '/topic/$slug'
    | '/admin-kb20/'
    | '/blog/'
    | '/admin-kb20/questions/$topic'
    | '/admin-kb20/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/all-tests'
    | '/bookmarks'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/exam-updates'
    | '/faq'
    | '/feedback'
    | '/forgot-password'
    | '/help'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/robots.txt'
    | '/seru-tfl'
    | '/signin'
    | '/signup'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/admin-kb20/diagnostics'
    | '/admin-kb20/login'
    | '/admin-kb20/users'
    | '/blog/$slug'
    | '/category/$slug'
    | '/guide/$slug'
    | '/quiz/$slug'
    | '/topic/$slug'
    | '/admin-kb20'
    | '/blog'
    | '/admin-kb20/questions/$topic'
    | '/admin-kb20/questions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/account'
    | '/admin'
    | '/all-tests'
    | '/blog'
    | '/bookmarks'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/disclaimer'
    | '/exam-updates'
    | '/faq'
    | '/feedback'
    | '/forgot-password'
    | '/help'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/robots.txt'
    | '/seru-tfl'
    | '/signin'
    | '/signup'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/admin-kb20/diagnostics'
    | '/admin-kb20/login'
    | '/admin-kb20/users'
    | '/blog/$slug'
    | '/category/$slug'
    | '/guide/$slug'
    | '/quiz/$slug'
    | '/topic/$slug'
    | '/admin-kb20/'
    | '/blog/'
    | '/admin-kb20/questions/$topic'
    | '/admin-kb20/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AllTestsRoute: typeof AllTestsRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ExamUpdatesRoute: typeof ExamUpdatesRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SeruTflRoute: typeof SeruTflRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminKb20DiagnosticsRoute: typeof AdminKb20DiagnosticsRoute
  AdminKb20LoginRoute: typeof AdminKb20LoginRoute
  AdminKb20UsersRoute: typeof AdminKb20UsersRoute
  CategorySlugRoute: typeof CategorySlugRoute
  GuideSlugRoute: typeof GuideSlugRoute
  QuizSlugRoute: typeof QuizSlugRoute
  TopicSlugRoute: typeof TopicSlugRoute
  AdminKb20IndexRoute: typeof AdminKb20IndexRoute
  AdminKb20QuestionsTopicRoute: typeof AdminKb20QuestionsTopicRoute
  AdminKb20QuestionsIndexRoute: typeof AdminKb20QuestionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seru-tfl': {
      id: '/seru-tfl'
      path: '/seru-tfl'
      fullPath: '/seru-tfl'
      preLoaderRoute: typeof SeruTflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-updates': {
      id: '/exam-updates'
      path: '/exam-updates'
      fullPath: '/exam-updates'
      preLoaderRoute: typeof ExamUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-tests': {
      id: '/all-tests'
      path: '/all-tests'
      fullPath: '/all-tests'
      preLoaderRoute: typeof AllTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin-kb20/': {
      id: '/admin-kb20/'
      path: '/admin-kb20'
      fullPath: '/admin-kb20/'
      preLoaderRoute: typeof AdminKb20IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/guide/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin-kb20/users': {
      id: '/admin-kb20/users'
      path: '/admin-kb20/users'
      fullPath: '/admin-kb20/users'
      preLoaderRoute: typeof AdminKb20UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kb20/login': {
      id: '/admin-kb20/login'
      path: '/admin-kb20/login'
      fullPath: '/admin-kb20/login'
      preLoaderRoute: typeof AdminKb20LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kb20/diagnostics': {
      id: '/admin-kb20/diagnostics'
      path: '/admin-kb20/diagnostics'
      fullPath: '/admin-kb20/diagnostics'
      preLoaderRoute: typeof AdminKb20DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kb20/questions/': {
      id: '/admin-kb20/questions/'
      path: '/admin-kb20/questions'
      fullPath: '/admin-kb20/questions/'
      preLoaderRoute: typeof AdminKb20QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kb20/questions/$topic': {
      id: '/admin-kb20/questions/$topic'
      path: '/admin-kb20/questions/$topic'
      fullPath: '/admin-kb20/questions/$topic'
      preLoaderRoute: typeof AdminKb20QuestionsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AllTestsRoute: AllTestsRoute,
  BlogRoute: BlogRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  ExamUpdatesRoute: ExamUpdatesRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SeruTflRoute: SeruTflRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminKb20DiagnosticsRoute: AdminKb20DiagnosticsRoute,
  AdminKb20LoginRoute: AdminKb20LoginRoute,
  AdminKb20UsersRoute: AdminKb20UsersRoute,
  CategorySlugRoute: CategorySlugRoute,
  GuideSlugRoute: GuideSlugRoute,
  QuizSlugRoute: QuizSlugRoute,
  TopicSlugRoute: TopicSlugRoute,
  AdminKb20IndexRoute: AdminKb20IndexRoute,
  AdminKb20QuestionsTopicRoute: AdminKb20QuestionsTopicRoute,
  AdminKb20QuestionsIndexRoute: AdminKb20QuestionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
