// Auto-generated by the admin CSV import tools.
// This harmless source-file change forces GitHub-to-Lovable sync after content imports.
export const LOVABLE_SYNC_TRIGGER = {
  lastNudge: "2026-06-05T17:43:19.749Z",
  reason: "mock-intros import: 270 rows, 6 topic(s)",
} as const;
