// Auto-generated by the admin CSV import tools.
// This harmless source-file change forces GitHub-to-Lovable sync after content imports.
export const LOVABLE_SYNC_TRIGGER = {
  lastNudge: "2026-06-04T19:28:36.058Z",
  reason: "mock-intros import: 5 rows, 1 topic(s)",
} as const;
