/**
 * Per-mock intro content shown on individual mock test start pages.
 * Keyed by topic slug then mock number. Used to give each mock page
 * unique body content for SEO and learner guidance.
 *
 * THIS FILE IS GENERATED by the admin "Mock Intros CSV Import" tool.
 * Edits made by hand will be overwritten on the next CSV commit unless
 * exported back through CSV first.
 */

export type Difficulty = "Beginner" | "Intermediate" | "Exam-ready";

export type PerMockFaq = { q: string; a: string };

export type PerMockIntro = {
  difficulty: Difficulty;
  covers: string;
  commonMistakes: string[];
  /** Optional per-mock topic bullets. Falls back to the topic-level intro list. */
  topicsIncluded?: string[];
  /** Optional per-mock "Who this mock is for" wording. */
  whoFor?: string;
  /** Optional per-mock FAQs (prepended ahead of topic-level FAQs at render time). */
  faqs?: PerMockFaq[];
};

export type RelatedGuide = { label: string; href: string; intro: string };

export const RELATED_GUIDE_BY_TOPIC: Record<string, RelatedGuide> = {
  "driving-theory": {
    label: "Driving Theory Test Guide",
    href: "/blog/driving-theory-test-questions",
    intro: "Read the Driving Theory Test Guide to revise key rules, road signs, hazards and safe driving topics before trying the next mock.",
  },
};

export const PER_MOCK_INTROS: Record<string, Record<number, PerMockIntro>> = {
  "driving-theory": {
    1: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 1 is a good starting point for learners beginning their UK driving theory revision. It covers foundation topics such as road signs, safe driving behaviour, speed awareness, road markings and basic hazard recognition. Use this test to check your general understanding before moving on to more challenging mocks.",
      commonMistakes: [
        "Rushing through simple road sign questions",
        "Missing words such as “must”, “should” or “never”",
        "Confusing warning signs with mandatory signs",
        "Guessing before reading all answer options",
      ],
      topicsIncluded: [
        "Foundation road signs and signals",
        "Basic safe driving behaviour",
        "Speed awareness on common road types",
        "Reading road markings",
        "First-look hazard recognition",
      ],
      whoFor: "Mock Test 1 suits learners starting their theory revision who want to build confidence with foundation road signs and basic safe behaviour before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 1 best for?",
          a: "Mock Test 1 is a beginner-level Driving Theory practice run focused on foundation road signs and basic safe behaviour. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    2: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 2 focuses on everyday driving knowledge, including road positioning, safe following distances, junction awareness and basic rules of the road. It is designed to help learners practise common theory-style questions and improve confidence with the types of decisions drivers need to make on UK roads.",
      commonMistakes: [
        "Choosing an answer too quickly at junction questions",
        "Forgetting to consider vulnerable road users",
        "Confusing stopping distance with thinking distance",
        "Not reviewing incorrect answers after finishing",
      ],
      topicsIncluded: [
        "Junction awareness and approach checks",
        "Safe following distances",
        "Basic road positioning",
        "Common rules of the road",
        "Awareness of vulnerable road users",
      ],
      whoFor: "Mock Test 2 suits learners starting their theory revision who want to build confidence with junction awareness and following distances before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 2 best for?",
          a: "Mock Test 2 is a beginner-level Driving Theory practice run focused on junction awareness and following distances. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    3: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 3 helps you practise key driving safety topics such as speed limits, traffic signs, pedestrian crossings and safe observation. This mock is useful for checking whether you understand basic road rules and can apply them to common driving situations.",
      commonMistakes: [
        "Mixing up speed limits on different road types",
        "Not spotting clues in pedestrian crossing questions",
        "Confusing circular and triangular signs",
        "Ignoring road condition details in the question",
      ],
      topicsIncluded: [
        "Speed limits on different road types",
        "Pedestrian crossings and right of way",
        "Basic traffic sign meanings",
        "Safe observation around schools and shops",
        "Reading clues in the question",
      ],
      whoFor: "Mock Test 3 suits learners starting their theory revision who want to build confidence with speed limits and pedestrian safety basics before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 3 best for?",
          a: "Mock Test 3 is a beginner-level Driving Theory practice run focused on speed limits and pedestrian safety basics. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    4: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 4 gives you more practice with essential learner driver topics, including road signs, lane discipline, parking awareness and safe vehicle control. It is suitable for early revision and helps you build a stronger base before attempting more scenario-based questions.",
      commonMistakes: [
        "Misreading lane discipline questions",
        "Forgetting basic parking safety checks",
        "Not linking road signs to their meaning",
        "Overlooking details about weather or traffic conditions",
      ],
      topicsIncluded: [
        "Lane discipline and road positioning",
        "Parking awareness and safety checks",
        "Essential road signs",
        "Safe vehicle control",
        "Early-stage learner driver decisions",
      ],
      whoFor: "Mock Test 4 suits learners starting their theory revision who want to build confidence with lane discipline and parking awareness before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 4 best for?",
          a: "Mock Test 4 is a beginner-level Driving Theory practice run focused on lane discipline and parking awareness. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    5: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 5 focuses on core driving knowledge such as observation, mirrors, signalling, road markings and safe behaviour around other vehicles. This mock helps learners practise the basics of safe decision-making and build confidence with multiple-choice theory questions.",
      commonMistakes: [
        "Forgetting mirror checks before changing direction",
        "Confusing road markings with road signs",
        "Selecting answers that sound safe but are incomplete",
        "Not checking whether the question asks for the safest option",
      ],
      topicsIncluded: [
        "Mirror, signal, manoeuvre routines",
        "Safe lane changes",
        "Reading road markings",
        "Awareness of nearby vehicles",
        "Choosing the safest of similar options",
      ],
      whoFor: "Mock Test 5 suits learners starting their theory revision who want to build confidence with mirrors, signals and basic manoeuvres before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 5 best for?",
          a: "Mock Test 5 is a beginner-level Driving Theory practice run focused on mirrors, signals and basic manoeuvres. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    6: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 6 covers important early-stage topics, including traffic lights, road signs, safe overtaking, vehicle awareness and dealing with pedestrians. It is designed to support regular revision and help you spot gaps in your knowledge before moving to harder mocks.",
      commonMistakes: [
        "Misunderstanding traffic light rules",
        "Overtaking when it would not be safe",
        "Not considering cyclists and pedestrians",
        "Guessing road sign meanings from colour alone",
      ],
      topicsIncluded: [
        "Traffic light meanings and sequences",
        "When and where it is safe to overtake",
        "Awareness of cyclists and pedestrians",
        "Identifying common road signs",
        "Behaviour at temporary traffic controls",
      ],
      whoFor: "Mock Test 6 suits learners starting their theory revision who want to build confidence with traffic lights and safe overtaking basics before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 6 best for?",
          a: "Mock Test 6 is a beginner-level Driving Theory practice run focused on traffic lights and safe overtaking basics. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    7: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 7 gives learners practice with common questions on speed, road signs, junctions, roundabouts and hazard awareness. It helps you build confidence with everyday driving situations and encourages careful reading of each answer option.",
      commonMistakes: [
        "Treating roundabout questions too casually",
        "Forgetting who may have priority",
        "Confusing advisory signs with rules",
        "Missing key words in longer questions",
      ],
      topicsIncluded: [
        "Roundabout approach and lane choice",
        "Priority rules at junctions",
        "Reading advisory versus mandatory signs",
        "Spotting clues in longer questions",
        "Confidence with basic theory wording",
      ],
      whoFor: "Mock Test 7 suits learners starting their theory revision who want to build confidence with roundabouts and priority basics before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 7 best for?",
          a: "Mock Test 7 is a beginner-level Driving Theory practice run focused on roundabouts and priority basics. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    8: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 8 focuses on safe driving habits, road positioning, signs, vehicle control and basic hazard awareness. It is useful for learners who want to strengthen their understanding of routine driving rules before attempting more challenging practice tests.",
      commonMistakes: [
        "Not checking road position clues",
        "Confusing “give way” and “stop” requirements",
        "Forgetting how weather affects driving",
        "Picking the first reasonable answer instead of the best one",
      ],
      topicsIncluded: [
        "Routine safe driving habits",
        "How weather affects driving",
        "Give way versus stop requirements",
        "Reading road position clues",
        "Choosing the best answer, not just a reasonable one",
      ],
      whoFor: "Mock Test 8 suits learners starting their theory revision who want to build confidence with routine driving habits and weather basics before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 8 best for?",
          a: "Mock Test 8 is a beginner-level Driving Theory practice run focused on routine driving habits and weather basics. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    9: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 9 helps you revise essential theory topics such as speed limits, warning signs, road markings, safety checks and responsible driving. Use this mock to practise accuracy and build a stronger foundation for exam-style driving theory questions.",
      commonMistakes: [
        "Mixing up warning and information signs",
        "Not reading the full scenario",
        "Forgetting basic vehicle safety checks",
        "Confusing legal requirements with good advice",
      ],
      topicsIncluded: [
        "Warning signs and what they mean",
        "Information versus instruction signs",
        "Basic vehicle safety checks",
        "Responsible driver behaviour",
        "Telling legal rules from good advice",
      ],
      whoFor: "Mock Test 9 suits learners starting their theory revision who want to build confidence with warning signs and responsible driving before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 9 best for?",
          a: "Mock Test 9 is a beginner-level Driving Theory practice run focused on warning signs and responsible driving. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    10: {
      difficulty: "Beginner",
      covers: "Driving Theory Mock Test 10 brings together foundation topics from earlier mocks, including signs, signals, road markings, safe speed and basic hazard awareness. It is a useful checkpoint before progressing to intermediate driving theory practice.",
      commonMistakes: [
        "Repeating the same mistakes from earlier mocks",
        "Confusing similar road sign shapes",
        "Not reviewing explanations after the test",
        "Underestimating simple-looking questions",
      ],
      topicsIncluded: [
        "Signs, signals and road markings recap",
        "Safe speed and stopping basics",
        "Foundation hazard awareness",
        "Routine vehicle safety checks",
        "Self-check before moving to intermediate mocks",
      ],
      whoFor: "Mock Test 10 suits learners starting their theory revision who want to build confidence with foundation checkpoint across earlier topics before moving on to more demanding mocks.",
      faqs: [
        {
          q: "What is Mock Test 10 best for?",
          a: "Mock Test 10 is a beginner-level Driving Theory practice run focused on foundation checkpoint across earlier topics. Use it as an early checkpoint while you're still building confidence with the basics.",
        },
      ],
    },
    11: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 11 introduces a stronger mix of scenario-style questions covering hazards, junctions, speed control, vulnerable road users and safe decision-making. It is designed for learners who already understand the basics and want to practise applying their knowledge.",
      commonMistakes: [
        "Not adjusting answers for weather or traffic conditions",
        "Forgetting cyclists and motorcyclists in hazard questions",
        "Choosing a legal option that is not the safest option",
        "Missing small details in scenario wording",
      ],
      topicsIncluded: [
        "Scenario-style hazard questions",
        "Junction safety in mixed conditions",
        "Speed control around vulnerable road users",
        "Reading scenario wording closely",
        "Choosing the safest, not just the legal, option",
      ],
      whoFor: "Mock Test 11 suits learners who know the basics and want scenario-style practice focused on scenario-style hazards and decision making alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 11 best for?",
          a: "Mock Test 11 is an intermediate-level Driving Theory mock focused on scenario-style hazards and decision making. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    12: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 12 focuses on practical driving judgement, including road positioning, overtaking, motorway awareness, pedestrian safety and traffic signs. This mock helps you practise making safe choices in realistic driving situations.",
      commonMistakes: [
        "Overtaking without enough safety margin",
        "Misunderstanding lane use on faster roads",
        "Forgetting pedestrian priority in some situations",
        "Not linking signs to road layout",
      ],
      topicsIncluded: [
        "Road positioning on faster roads",
        "Safe overtaking judgement",
        "Motorway and dual carriageway awareness",
        "Pedestrian safety in built-up areas",
        "Linking signs to the road layout",
      ],
      whoFor: "Mock Test 12 suits learners who know the basics and want scenario-style practice focused on practical driving judgement on faster roads alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 12 best for?",
          a: "Mock Test 12 is an intermediate-level Driving Theory mock focused on practical driving judgement on faster roads. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    13: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 13 covers a balanced mix of road safety, signs, crossings, vehicle handling and hazard awareness. It is useful for learners who want to improve consistency and reduce careless mistakes across different theory topics.",
      commonMistakes: [
        "Confusing different types of pedestrian crossing",
        "Ignoring road surface or weather clues",
        "Not checking whether the question asks what to do first",
        "Choosing answers based on habit instead of rules",
      ],
      topicsIncluded: [
        "Types of pedestrian crossing",
        "Vehicle handling in poor weather",
        "Reading road surface clues",
        "First-action versus best-action questions",
        "Rules over habit in mixed scenarios",
      ],
      whoFor: "Mock Test 13 suits learners who know the basics and want scenario-style practice focused on crossings, vehicle handling and consistency alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 13 best for?",
          a: "Mock Test 13 is an intermediate-level Driving Theory mock focused on crossings, vehicle handling and consistency. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    14: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 14 helps you practise questions on speed, stopping distances, safe following gaps, road signs and driver responsibility. It is designed to improve your ability to apply safety rules rather than simply memorise answers.",
      commonMistakes: [
        "Confusing thinking distance and braking distance",
        "Forgetting that poor weather increases stopping distance",
        "Choosing answers that are too aggressive",
        "Not spotting “except” or “most likely” wording",
      ],
      topicsIncluded: [
        "Thinking and braking distance components",
        "How weather changes stopping distance",
        "Safe following gaps in traffic",
        "Driver responsibility for speed",
        "Spotting wording like “except” and “most likely”",
      ],
      whoFor: "Mock Test 14 suits learners who know the basics and want scenario-style practice focused on speed, stopping distances and following gaps alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 14 best for?",
          a: "Mock Test 14 is an intermediate-level Driving Theory mock focused on speed, stopping distances and following gaps. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    15: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 15 focuses on safe road use, including junction decisions, traffic signs, roundabouts, vulnerable road users and responsible behaviour. This mock is useful for learners preparing to move from basic recall to more applied driving theory practice.",
      commonMistakes: [
        "Misjudging priority at junctions",
        "Forgetting to check mirrors and blind spots",
        "Confusing road signs with similar colours",
        "Not considering what other road users may do",
      ],
      topicsIncluded: [
        "Priority decisions at junctions",
        "Roundabout lane choice and signalling",
        "Mirror and blind-spot routines",
        "Telling apart signs with similar colours",
        "Anticipating other road users",
      ],
      whoFor: "Mock Test 15 suits learners who know the basics and want scenario-style practice focused on junction decisions and roundabout strategy alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 15 best for?",
          a: "Mock Test 15 is an intermediate-level Driving Theory mock focused on junction decisions and roundabout strategy. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    16: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 16 includes questions on hazard perception knowledge, road signs, lane discipline, speed awareness and safe reactions. It helps learners practise careful decision-making and identify areas where more revision may be needed.",
      commonMistakes: [
        "Reacting too late in hazard-style questions",
        "Not recognising developing hazards",
        "Misunderstanding lane arrows and markings",
        "Ignoring the safest response in favour of the quickest",
      ],
      topicsIncluded: [
        "Developing versus static hazards",
        "Lane arrows and road markings",
        "Speed awareness in hazard questions",
        "Safe reactions to changing conditions",
        "Reviewing weak hazard areas",
      ],
      whoFor: "Mock Test 16 suits learners who know the basics and want scenario-style practice focused on hazard perception knowledge and reactions alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 16 best for?",
          a: "Mock Test 16 is an intermediate-level Driving Theory mock focused on hazard perception knowledge and reactions. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    17: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 17 covers mixed driving theory topics such as road signs, vehicle safety, speed limits, crossings and road user awareness. It is designed to help learners practise a wider range of questions in one sitting.",
      commonMistakes: [
        "Confusing vehicle safety checks",
        "Forgetting rules around crossings",
        "Not reading the context before choosing",
        "Treating all road sign questions as simple memory questions",
      ],
      topicsIncluded: [
        "Mixed road sign recognition",
        "Vehicle safety checks and warning lights",
        "Speed limits across settings",
        "Crossings and road user priority",
        "Reading question context, not just keywords",
      ],
      whoFor: "Mock Test 17 suits learners who know the basics and want scenario-style practice focused on mixed road signs, vehicle safety and crossings alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 17 best for?",
          a: "Mock Test 17 is an intermediate-level Driving Theory mock focused on mixed road signs, vehicle safety and crossings. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    18: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 18 focuses on road safety decisions, including when to slow down, when to give way, how to respond to hazards and how to drive safely around pedestrians, cyclists and motorcyclists.",
      commonMistakes: [
        "Not slowing down early enough in scenarios",
        "Forgetting vulnerable road users need extra space",
        "Choosing answers that increase risk",
        "Missing clues about limited visibility",
      ],
      topicsIncluded: [
        "Knowing when to slow down early",
        "Giving way in scenario questions",
        "Safe space around cyclists and motorcyclists",
        "Driving around pedestrians safely",
        "Spotting clues about limited visibility",
      ],
      whoFor: "Mock Test 18 suits learners who know the basics and want scenario-style practice focused on slowing down, giving way and vulnerable users alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 18 best for?",
          a: "Mock Test 18 is an intermediate-level Driving Theory mock focused on slowing down, giving way and vulnerable users. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    19: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 19 helps you revise key areas such as road markings, motorway rules, signs, speed control and hazard awareness. It is useful for learners who want more practice with mixed-topic theory questions.",
      commonMistakes: [
        "Misreading road markings",
        "Confusing motorway lane rules",
        "Not adjusting speed for conditions",
        "Overlooking warning signs in the question",
      ],
      topicsIncluded: [
        "Reading road markings accurately",
        "Motorway lane and slip-road rules",
        "Speed control for conditions",
        "Warning signs in mixed scenarios",
        "Building consistency across topics",
      ],
      whoFor: "Mock Test 19 suits learners who know the basics and want scenario-style practice focused on road markings, motorway rules and mixed topics alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 19 best for?",
          a: "Mock Test 19 is an intermediate-level Driving Theory mock focused on road markings, motorway rules and mixed topics. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    20: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 20 is a mid-point revision test covering road signs, safety margins, driver attitude, legal responsibilities and practical driving decisions. Use this mock to check how well you are retaining earlier topics.",
      commonMistakes: [
        "Forgetting legal responsibilities",
        "Not keeping a safe separation distance",
        "Choosing impatient or risky actions",
        "Failing to review repeated weak areas",
      ],
      topicsIncluded: [
        "Safety margins in different scenarios",
        "Driver attitude and patience",
        "Legal responsibilities of the driver",
        "Practical driving decisions",
        "Self-check on earlier topics",
      ],
      whoFor: "Mock Test 20 suits learners who know the basics and want scenario-style practice focused on mid-point checkpoint with attitude and legal rules alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 20 best for?",
          a: "Mock Test 20 is an intermediate-level Driving Theory mock focused on mid-point checkpoint with attitude and legal rules. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    21: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 21 gives practice with more applied questions on hazards, road positioning, crossings, signs and safe driving behaviour. It is designed to help learners improve judgement in situations where more than one answer may seem possible.",
      commonMistakes: [
        "Choosing a possible answer instead of the safest answer",
        "Missing clues about road users nearby",
        "Confusing road sign instructions",
        "Not thinking ahead in hazard questions",
      ],
      topicsIncluded: [
        "Picking the safest of several plausible options",
        "Spotting nearby road users",
        "Interpreting road sign instructions",
        "Looking ahead in hazard questions",
        "Avoiding habit-based answers",
      ],
      whoFor: "Mock Test 21 suits learners who know the basics and want scenario-style practice focused on judgement when multiple answers seem possible alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 21 best for?",
          a: "Mock Test 21 is an intermediate-level Driving Theory mock focused on judgement when multiple answers seem possible. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    22: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 22 focuses on safe choices in everyday road situations, including junctions, traffic signs, speed, observation and responsible driving. It helps learners practise both knowledge and judgement.",
      commonMistakes: [
        "Misreading junction layouts",
        "Forgetting observation checks",
        "Confusing speed guidance with speed limits",
        "Not considering road conditions",
      ],
      topicsIncluded: [
        "Junction safety and observation",
        "Speed choices in everyday situations",
        "Traffic signs and road rules",
        "Responsible driving behaviour",
        "Scenario-based road judgement",
      ],
      whoFor: "Mock Test 22 suits learners who know the basics and want scenario-style practice focused on junction safety and everyday speed choices alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 22 best for?",
          a: "Mock Test 22 is an intermediate-level Driving Theory mock focused on junction safety and everyday speed choices. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    23: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 23 covers a useful mix of road signs, hazard awareness, vehicle safety, driver behaviour and traffic rules. This mock helps build confidence by testing a wider range of theory knowledge.",
      commonMistakes: [
        "Forgetting vehicle maintenance basics",
        "Missing the safest action in hazard questions",
        "Confusing similar signs or markings",
        "Not reading all answer options fully",
      ],
      topicsIncluded: [
        "Mixed road sign recall",
        "Basic vehicle maintenance",
        "Hazard awareness in unfamiliar settings",
        "Safer driver behaviour",
        "Reading every option before answering",
      ],
      whoFor: "Mock Test 23 suits learners who know the basics and want scenario-style practice focused on mixed signs, vehicle safety and driver behaviour alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 23 best for?",
          a: "Mock Test 23 is an intermediate-level Driving Theory mock focused on mixed signs, vehicle safety and driver behaviour. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    24: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 24 helps learners practise questions on road safety, crossings, signs, stopping distances and driving responsibly around other road users. It is suitable for building accuracy before moving into more exam-ready mocks.",
      commonMistakes: [
        "Confusing crossing types",
        "Underestimating stopping distances",
        "Not leaving enough space for cyclists",
        "Selecting answers based on memory rather than context",
      ],
      topicsIncluded: [
        "Different crossing types and rules",
        "Stopping distance in traffic",
        "Safe space for cyclists",
        "Sharing the road responsibly",
        "Context over memorised answers",
      ],
      whoFor: "Mock Test 24 suits learners who know the basics and want scenario-style practice focused on crossings, stopping distance and shared roads alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 24 best for?",
          a: "Mock Test 24 is an intermediate-level Driving Theory mock focused on crossings, stopping distance and shared roads. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    25: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 25 focuses on mixed driving theory knowledge, including road signs, legal rules, speed control, hazards and safer driving attitudes. This mock is useful for checking whether you can apply your revision across different question types.",
      commonMistakes: [
        "Forgetting legal rule wording",
        "Rushing mixed-topic questions",
        "Not identifying the main risk in a scenario",
        "Confusing advice with legal requirements",
      ],
      topicsIncluded: [
        "Legal rule wording in theory questions",
        "Telling legal requirements from advice",
        "Speed control across road types",
        "Hazards in mixed conditions",
        "Calmer, safer driving attitudes",
      ],
      whoFor: "Mock Test 25 suits learners who know the basics and want scenario-style practice focused on legal rules, advice and safer attitudes alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 25 best for?",
          a: "Mock Test 25 is an intermediate-level Driving Theory mock focused on legal rules, advice and safer attitudes. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    26: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 26 covers practical road awareness, including lane use, speed, road signs, junctions and safe responses to other road users. It helps learners practise calm, safe decision-making under quiz conditions.",
      commonMistakes: [
        "Choosing unsafe lane changes",
        "Not checking mirrors in the correct situations",
        "Missing road layout clues",
        "Ignoring pedestrians or cyclists in the scenario",
      ],
      topicsIncluded: [
        "Safe lane changes and lane discipline",
        "When to check mirrors",
        "Reading the road layout",
        "Awareness of pedestrians and cyclists",
        "Calm decisions under quiz pressure",
      ],
      whoFor: "Mock Test 26 suits learners who know the basics and want scenario-style practice focused on lane use, mirrors and calm decision making alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 26 best for?",
          a: "Mock Test 26 is an intermediate-level Driving Theory mock focused on lane use, mirrors and calm decision making. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    27: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 27 includes questions on safe driving behaviour, signs, road markings, vehicle control and hazard awareness. It is designed to help learners improve consistency and reduce errors caused by rushing.",
      commonMistakes: [
        "Misreading road markings",
        "Not slowing down for developing hazards",
        "Choosing answers that are too vague",
        "Forgetting to use explanations for revision",
      ],
      topicsIncluded: [
        "Reading road markings carefully",
        "Slowing down for developing hazards",
        "Avoiding vague or partial answers",
        "Using explanations for revision",
        "Improving consistency across topics",
      ],
      whoFor: "Mock Test 27 suits learners who know the basics and want scenario-style practice focused on markings, hazards and avoiding rushed errors alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 27 best for?",
          a: "Mock Test 27 is an intermediate-level Driving Theory mock focused on markings, hazards and avoiding rushed errors. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    28: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 28 focuses on decision-making in common driving situations, including junctions, roundabouts, speed, signs and vulnerable road users. It helps learners practise recognising the safest response.",
      commonMistakes: [
        "Misjudging priority",
        "Forgetting to allow extra space",
        "Confusing similar road sign meanings",
        "Picking an answer before understanding the scenario",
      ],
      topicsIncluded: [
        "Priority decisions at junctions and roundabouts",
        "Leaving space for vulnerable road users",
        "Telling apart similar sign meanings",
        "Reading scenario context fully",
        "Picking the safest response",
      ],
      whoFor: "Mock Test 28 suits learners who know the basics and want scenario-style practice focused on junctions, roundabouts and vulnerable users alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 28 best for?",
          a: "Mock Test 28 is an intermediate-level Driving Theory mock focused on junctions, roundabouts and vulnerable users. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    29: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 29 covers signs, hazard awareness, vehicle safety, speed and responsible driver behaviour. Use this test to strengthen your recall and improve your ability to apply theory knowledge to road situations.",
      commonMistakes: [
        "Confusing warning signs and information signs",
        "Forgetting vehicle safety checks",
        "Not adapting speed to conditions",
        "Missing key details in longer questions",
      ],
      topicsIncluded: [
        "Warning signs versus information signs",
        "Vehicle safety responsibilities",
        "Adapting speed to conditions",
        "Reading the full scenario",
        "Applying knowledge under quiz pace",
      ],
      whoFor: "Mock Test 29 suits learners who know the basics and want scenario-style practice focused on signs, hazards and adapting to conditions alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 29 best for?",
          a: "Mock Test 29 is an intermediate-level Driving Theory mock focused on signs, hazards and adapting to conditions. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    30: {
      difficulty: "Intermediate",
      covers: "Driving Theory Mock Test 30 is a strong revision checkpoint covering road signs, hazards, safety rules, driving attitude and common road situations. It is useful before attempting the more exam-ready practice tests.",
      commonMistakes: [
        "Repeating earlier weak areas",
        "Not checking explanations carefully",
        "Confusing road safety guidance",
        "Losing marks through careless reading",
      ],
      topicsIncluded: [
        "Road signs and rules of the road recap",
        "Hazard awareness in varied scenarios",
        "Driving attitude and patience",
        "Reviewing earlier weak areas",
        "Self-check before exam-ready mocks",
      ],
      whoFor: "Mock Test 30 suits learners who know the basics and want scenario-style practice focused on pre-exam checkpoint across mixed topics alongside other mixed-topic questions.",
      faqs: [
        {
          q: "What is Mock Test 30 best for?",
          a: "Mock Test 30 is an intermediate-level Driving Theory mock focused on pre-exam checkpoint across mixed topics. Use it once you've handled the early mocks and want more applied, scenario-style questions.",
        },
      ],
    },
    31: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 31 is aimed at learners who are moving towards exam-ready practice. It includes a broader mix of signs, hazards, road rules, speed awareness and scenario-based questions that require careful judgement.",
      commonMistakes: [
        "Rushing under time pressure",
        "Missing small wording differences",
        "Not choosing the safest option",
        "Forgetting to review weaker topics after finishing",
      ],
      topicsIncluded: [
        "Mixed signs, hazards and road rules",
        "Speed awareness in scenario questions",
        "Careful judgement under time pressure",
        "Spotting small wording differences",
        "Reviewing weaker topics after each attempt",
      ],
      whoFor: "Mock Test 31 suits learners close to test day who want to check accuracy, timing and confidence on move into exam-ready mixed practice as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 31 best for?",
          a: "Mock Test 31 is an exam-ready Driving Theory mock focused on move into exam-ready mixed practice. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    32: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 32 focuses on applying theory knowledge across mixed road situations, including hazards, junctions, road signs, vehicle safety and safe driving behaviour. It is designed to test readiness across several common topics.",
      commonMistakes: [
        "Treating scenario questions like memory questions",
        "Not spotting the main hazard",
        "Confusing similar answer options",
        "Choosing a risky action because it seems faster",
      ],
      topicsIncluded: [
        "Applying theory to scenario questions",
        "Spotting the main hazard in a scene",
        "Telling apart similar answer options",
        "Choosing safety over speed",
        "Junction and sign decisions in mixed conditions",
      ],
      whoFor: "Mock Test 32 suits learners close to test day who want to check accuracy, timing and confidence on applying theory across mixed road situations as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 32 best for?",
          a: "Mock Test 32 is an exam-ready Driving Theory mock focused on applying theory across mixed road situations. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    33: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 33 gives learners more challenging practice with road signs, speed control, crossings, hazards and road user awareness. It helps you check whether your theory knowledge is accurate under mixed-question conditions.",
      commonMistakes: [
        "Confusing speed rules in different settings",
        "Not reading crossing questions carefully",
        "Missing road user clues",
        "Overlooking weather or visibility details",
      ],
      topicsIncluded: [
        "Speed rules in different settings",
        "Crossing types under exam-style pressure",
        "Road user awareness clues",
        "Weather and visibility details",
        "Mixed-question consistency",
      ],
      whoFor: "Mock Test 33 suits learners close to test day who want to check accuracy, timing and confidence on challenging mix of signs, speed and crossings as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 33 best for?",
          a: "Mock Test 33 is an exam-ready Driving Theory mock focused on challenging mix of signs, speed and crossings. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    34: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 34 covers a challenging mix of driving theory topics, including legal responsibilities, hazard awareness, signs, markings and safe reactions. It is useful for learners who want to practise more careful, exam-style decision-making.",
      commonMistakes: [
        "Confusing legal rules with general advice",
        "Choosing the quickest response rather than the safest",
        "Missing road marking details",
        "Not reviewing questions answered incorrectly",
      ],
      topicsIncluded: [
        "Legal rules versus general guidance",
        "Hazard awareness in built-up areas",
        "Reading road markings precisely",
        "Safer reactions over faster ones",
        "Reviewing every incorrect answer",
      ],
      whoFor: "Mock Test 34 suits learners close to test day who want to check accuracy, timing and confidence on legal rules, hazards and careful reactions as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 34 best for?",
          a: "Mock Test 34 is an exam-ready Driving Theory mock focused on legal rules, hazards and careful reactions. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    35: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 35 focuses on road safety, signs, junction decisions, speed awareness and responsible driving behaviour. It helps learners practise applying knowledge to varied situations instead of relying only on memorised answers.",
      commonMistakes: [
        "Misjudging junction priority",
        "Confusing road sign instructions",
        "Not allowing enough safety margin",
        "Missing wording such as “first” or “most important”",
      ],
      topicsIncluded: [
        "Junction priority decisions",
        "Reading road sign instructions",
        "Safety margins in tight scenarios",
        "Picking out wording like “first” or “most important”",
        "Responsible driver behaviour under pressure",
      ],
      whoFor: "Mock Test 35 suits learners close to test day who want to check accuracy, timing and confidence on road safety, junctions and safety margins as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 35 best for?",
          a: "Mock Test 35 is an exam-ready Driving Theory mock focused on road safety, junctions and safety margins. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    36: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 36 gives exam-ready practice across topics such as hazard recognition, road positioning, vulnerable road users, road signs and safe vehicle use. This mock is useful for identifying final revision gaps.",
      commonMistakes: [
        "Not recognising developing hazards",
        "Forgetting extra care around cyclists and pedestrians",
        "Confusing signs that look similar",
        "Ignoring explanations after the test",
      ],
      topicsIncluded: [
        "Recognising developing hazards",
        "Extra care around cyclists and pedestrians",
        "Telling apart visually similar signs",
        "Safe vehicle use in mixed conditions",
        "Final gap-spotting before booking the test",
      ],
      whoFor: "Mock Test 36 suits learners close to test day who want to check accuracy, timing and confidence on hazard recognition and vulnerable road users as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 36 best for?",
          a: "Mock Test 36 is an exam-ready Driving Theory mock focused on hazard recognition and vulnerable road users. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    37: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 37 focuses on mixed-topic revision with questions covering signs, speed, safety distances, road markings, hazards and driver responsibility. It is designed to help learners practise accuracy and consistency.",
      commonMistakes: [
        "Miscalculating safety distances",
        "Not adjusting for road conditions",
        "Confusing road markings with signs",
        "Selecting the answer that sounds familiar rather than correct",
      ],
      topicsIncluded: [
        "Calculating safety distances",
        "Adjusting for road conditions",
        "Markings versus signs in scenarios",
        "Choosing the correct over the familiar answer",
        "Improving accuracy under exam pace",
      ],
      whoFor: "Mock Test 37 suits learners close to test day who want to check accuracy, timing and confidence on safety distances, markings and accuracy drill as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 37 best for?",
          a: "Mock Test 37 is an exam-ready Driving Theory mock focused on safety distances, markings and accuracy drill. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    38: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 38 helps you practise more advanced decision-making across road signs, junctions, hazards, motorway awareness and safe driving behaviour. It is useful for building confidence before timed exam mode.",
      commonMistakes: [
        "Misunderstanding motorway lane use",
        "Not spotting the safest response at junctions",
        "Forgetting mirror and blind spot checks",
        "Rushing longer scenario questions",
      ],
      topicsIncluded: [
        "Motorway lane use and overtaking",
        "Safer responses at busy junctions",
        "Mirror and blind-spot checks",
        "Handling longer scenario questions",
        "Building timed-exam confidence",
      ],
      whoFor: "Mock Test 38 suits learners close to test day who want to check accuracy, timing and confidence on junctions, motorways and timed-exam confidence as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 38 best for?",
          a: "Mock Test 38 is an exam-ready Driving Theory mock focused on junctions, motorways and timed-exam confidence. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    39: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 39 includes challenging practice on hazards, signs, road rules, vehicle control and safety awareness. It is designed to help learners test their readiness across a wider range of theory topics.",
      commonMistakes: [
        "Not identifying the highest-risk hazard",
        "Confusing similar traffic signs",
        "Forgetting safe control in poor conditions",
        "Not reading the full question before answering",
      ],
      topicsIncluded: [
        "Identifying the highest-risk hazard",
        "Vehicle control in poor conditions",
        "Telling apart similar traffic signs",
        "Sign meanings in mixed scenarios",
        "Reading every full question",
      ],
      whoFor: "Mock Test 39 suits learners close to test day who want to check accuracy, timing and confidence on hazards, vehicle control and signs under pressure as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 39 best for?",
          a: "Mock Test 39 is an exam-ready Driving Theory mock focused on hazards, vehicle control and signs under pressure. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    40: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 40 is a strong exam-ready revision test covering signs, stopping distances, road markings, vulnerable road users and practical safety decisions. Use this mock to check your progress before attempting final practice tests.",
      commonMistakes: [
        "Underestimating stopping distance questions",
        "Forgetting the needs of vulnerable road users",
        "Misreading markings or lane arrows",
        "Not learning from repeated incorrect answers",
      ],
      topicsIncluded: [
        "Stopping distance questions",
        "Needs of vulnerable road users",
        "Reading markings and lane arrows",
        "Learning from repeated incorrect answers",
        "Progress check before final mocks",
      ],
      whoFor: "Mock Test 40 suits learners close to test day who want to check accuracy, timing and confidence on signs, stopping distances and vulnerable users as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 40 best for?",
          a: "Mock Test 40 is an exam-ready Driving Theory mock focused on signs, stopping distances and vulnerable users. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    41: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 41 focuses on final-stage revision, with questions covering road signs, hazards, driver attitude, legal rules and safe decision-making. It helps learners practise staying accurate across different theory areas.",
      commonMistakes: [
        "Losing marks through rushed reading",
        "Confusing legal wording",
        "Choosing answers that are not defensive enough",
        "Forgetting to review weak topics after finishing",
      ],
      topicsIncluded: [
        "Final-stage road signs",
        "Hazard scenarios in mixed conditions",
        "Driver attitude and patience",
        "Legal rule wording",
        "Defensive decision-making",
      ],
      whoFor: "Mock Test 41 suits learners close to test day who want to check accuracy, timing and confidence on driver attitude and legal rule wording as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 41 best for?",
          a: "Mock Test 41 is an exam-ready Driving Theory mock focused on driver attitude and legal rule wording. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    42: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 42 gives advanced practice with mixed questions on road signs, safety, speed, junctions and hazard awareness. It is suitable for learners who want to test their confidence before using full exam mode.",
      commonMistakes: [
        "Misreading complex scenarios",
        "Not considering all road users",
        "Choosing answers based on habit",
        "Missing clues about road conditions",
      ],
      topicsIncluded: [
        "Mixed road signs at speed",
        "Speed and stopping in scenarios",
        "Junction decisions under exam pace",
        "Hazard awareness across road types",
        "Building exam-mode confidence",
      ],
      whoFor: "Mock Test 42 suits learners close to test day who want to check accuracy, timing and confidence on mixed signs, speed, junctions and hazards as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 42 best for?",
          a: "Mock Test 42 is an exam-ready Driving Theory mock focused on mixed signs, speed, junctions and hazards. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    43: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 43 focuses on high-confidence revision across road signs, safe driving behaviour, hazards, vehicle awareness and road rules. It helps learners sharpen their accuracy and reduce avoidable mistakes.",
      commonMistakes: [
        "Confusing similar road signs",
        "Not identifying the safest action",
        "Forgetting vehicle safety responsibilities",
        "Rushing because the topic looks familiar",
      ],
      topicsIncluded: [
        "Sharper road sign recall",
        "Safest action in each scenario",
        "Vehicle safety responsibilities",
        "Avoiding rushed familiar-topic mistakes",
        "Steady accuracy across the test",
      ],
      whoFor: "Mock Test 43 suits learners close to test day who want to check accuracy, timing and confidence on high-confidence revision across key topics as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 43 best for?",
          a: "Mock Test 43 is an exam-ready Driving Theory mock focused on high-confidence revision across key topics. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    44: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 44 is designed for final-stage practice and includes a varied mix of signs, hazards, traffic rules, speed awareness and safe driving decisions. Use it to check whether your revision is consistent across different topics.",
      commonMistakes: [
        "Overlooking small wording changes",
        "Not adapting answers to the scenario",
        "Confusing road markings and sign instructions",
        "Failing to revisit incorrect answers",
      ],
      topicsIncluded: [
        "Small wording changes in scenarios",
        "Adapting answers to the scene",
        "Markings versus sign instructions",
        "Hazards across rural and urban roads",
        "Final consistency check",
      ],
      whoFor: "Mock Test 44 suits learners close to test day who want to check accuracy, timing and confidence on final-stage mixed signs, hazards and decisions as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 44 best for?",
          a: "Mock Test 44 is an exam-ready Driving Theory mock focused on final-stage mixed signs, hazards and decisions. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
    45: {
      difficulty: "Exam-ready",
      covers: "Driving Theory Mock Test 45 is a final revision mock for learners preparing for timed exam-style practice. It covers a broad mix of road signs, safety rules, hazards, road markings, speed awareness and responsible driving behaviour.",
      commonMistakes: [
        "Rushing because it is the final mock",
        "Forgetting to check all answer options",
        "Missing key safety details in scenarios",
        "Not using the results to plan final revision",
      ],
      topicsIncluded: [
        "Final-stage Driving Theory revision",
        "Mixed road signs and safety rules",
        "Hazard awareness and safe decisions",
        "Speed, stopping distance and road conditions",
        "Last-check learner driver knowledge",
      ],
      whoFor: "Mock Test 45 suits learners close to test day who want to check accuracy, timing and confidence on last-check driving theory revision as part of mixed final revision.",
      faqs: [
        {
          q: "What is Mock Test 45 best for?",
          a: "Mock Test 45 is an exam-ready Driving Theory mock focused on last-check driving theory revision. Use it as final-stage revision to check accuracy and timing close to test day.",
        },
      ],
    },
  },
  "hazard-perception": {
    1: {
      difficulty: "Beginner",
      covers: "Hazard Perception Mock Test 1 introduces the basics of spotting developing hazards, such as pedestrians near the road, vehicles changing speed, junction risks and situations where you may need to slow down early. It is designed to help learners understand what a developing hazard looks like before moving on to more challenging clips and scenarios.",
      commonMistakes: [
        "Clicking too early before the hazard develops",
        "Clicking repeatedly without thinking",
        "Missing pedestrians or cyclists near junctions",
        "Not scanning the whole road scene",
      ],
      topicsIncluded: [
        "Recognising developing hazards",
        "Pedestrians near the road",
        "Junction awareness",
        "Early speed adjustment",
        "Scanning ahead for risk",
      ],
      whoFor: "This mock is best for learner drivers who are new to hazard perception practice and want to build confidence with simple developing hazards and safe observation habits.",
      faqs: [
        {
          q: "What does Hazard Perception Mock Test 1 cover?",
          a: "Mock Test 1 focuses on beginner hazard perception skills, including spotting developing hazards, reacting to pedestrians, noticing junction risks and learning when a situation may require you to slow down.",
        },
        {
          q: "Is this an official DVSA hazard perception test?",
          a: "No. This is independent hazard perception practice designed to help learners revise and build confidence. It is not an official DVSA test.",
        },
        {
          q: "How should I use this mock?",
          a: "Use this mock to practise spotting hazards early, then review your result and focus on the situations you missed before moving to the next mock.",
        },
      ],
    },
    2: {
      difficulty: "Beginner",
      covers: "Hazard Perception Mock Test 2 focuses on everyday road situations where risks can develop quickly, including parked vehicles, changing traffic flow, cyclists, pedestrians and junction approaches. This mock helps learners practise watching the road ahead, identifying possible dangers and responding before the situation becomes more serious.",
      commonMistakes: [
        "Focusing only on the vehicle directly ahead",
        "Missing hazards caused by parked cars",
        "Reacting late to cyclists or pedestrians",
        "Forgetting to watch junctions and side roads",
      ],
      topicsIncluded: [
        "Parked vehicle hazards",
        "Cyclists and vulnerable road users",
        "Changing traffic conditions",
        "Side road and junction risks",
        "Observation and anticipation",
      ],
      whoFor: "This mock is suitable for learners who understand the basics and want more practice recognising common hazards in normal road and traffic situations.",
      faqs: [
        {
          q: "What does Hazard Perception Mock Test 2 help me practise?",
          a: "Mock Test 2 helps you practise spotting hazards linked to parked vehicles, cyclists, pedestrians, side roads and changing traffic conditions.",
        },
        {
          q: "Can I retake this hazard perception mock?",
          a: "Yes. Retaking the mock can help you notice patterns in the hazards you miss and improve your timing and observation.",
        },
        {
          q: "What should I focus on during this mock?",
          a: "Focus on the whole road scene, not just the vehicle in front. Watch pavements, junctions, parked cars and vulnerable road users.",
        },
      ],
    },
    3: {
      difficulty: "Beginner",
      covers: "Hazard Perception Mock Test 3 gives learners more practice with developing hazards involving road users, visibility, traffic movement and changing road layouts. It encourages careful observation, earlier reactions and better awareness of how small changes in a road scene can become hazards.",
      commonMistakes: [
        "Waiting until the hazard is obvious before reacting",
        "Not noticing changes in traffic speed",
        "Missing clues from road layout or visibility",
        "Clicking without identifying the actual developing hazard",
      ],
      topicsIncluded: [
        "Developing traffic hazards",
        "Visibility and road layout clues",
        "Pedestrian and vehicle movement",
        "Speed changes ahead",
        "Hazard timing and awareness",
      ],
      whoFor: "This mock is for learner drivers who want to strengthen early hazard recognition and improve their ability to notice risks before they fully develop.",
      faqs: [
        {
          q: "What does Hazard Perception Mock Test 3 cover?",
          a: "Mock Test 3 focuses on developing traffic hazards, visibility clues, road layout changes and timing your response when a risk begins to develop.",
        },
        {
          q: "Why is timing important in hazard perception?",
          a: "Timing matters because the aim is to recognise a developing hazard early enough, not after the danger has already become obvious.",
        },
        {
          q: "What should I do after finishing this mock?",
          a: "Review the hazards you missed, then practise again while focusing on earlier observation, traffic movement and clues from the road environment.",
        },
      ],
    },
  },
};

export function getPerMockIntro(
  topicSlug: string,
  mockNumber: number,
): PerMockIntro | undefined {
  return PER_MOCK_INTROS[topicSlug]?.[mockNumber];
}

export function getRelatedGuide(topicSlug: string): RelatedGuide | undefined {
  return RELATED_GUIDE_BY_TOPIC[topicSlug];
}
